//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_PIItem
    {
        public EXP_PIItem()
        {
            this.EXP_PIItemColor = new HashSet<EXP_PIItemColor>();
        }
    
        public long PIItemID { get; set; }
        public Nullable<long> PIID { get; set; }
        public string Commodity { get; set; }
        public string HSCode { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string ArticleNo { get; set; }
        public Nullable<byte> ItemTypeID { get; set; }
        public Nullable<byte> LeatherTypeID { get; set; }
        public Nullable<byte> LeatherStatusID { get; set; }
        public string AvgSize { get; set; }
        public Nullable<byte> AvgSizeUnit { get; set; }
        public string SideDescription { get; set; }
        public string SelectionRange { get; set; }
        public string Thickness { get; set; }
        public Nullable<byte> ThicknessUnit { get; set; }
        public string ThicknessAt { get; set; }
        public Nullable<System.DateTime> ItemDeliveryDate { get; set; }
        public string ApprovalState { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> ArticleFootQty { get; set; }
        public Nullable<decimal> SeaFootUnitPrice { get; set; }
        public Nullable<decimal> SeaFootTotalPrice { get; set; }
        public Nullable<decimal> AirFootUnitPrice { get; set; }
        public Nullable<decimal> AirFootTotalPrice { get; set; }
        public Nullable<decimal> RoadFootUnitPrice { get; set; }
        public Nullable<decimal> RoadFootTotalPrice { get; set; }
        public Nullable<decimal> ArticleMeterQty { get; set; }
        public Nullable<decimal> SeaMeterUnitPrice { get; set; }
        public Nullable<decimal> SeaMeterTotalPrice { get; set; }
        public Nullable<decimal> AirMeterUnitPrice { get; set; }
        public Nullable<decimal> AirMeterTotalPrice { get; set; }
        public Nullable<decimal> RoadMeterUnitPrice { get; set; }
        public Nullable<decimal> RoadMeterTotalPrice { get; set; }
    
        public virtual EXP_LeatherPI EXP_LeatherPI { get; set; }
        public virtual Sys_Article Sys_Article { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual Sys_LeatherStatus Sys_LeatherStatus { get; set; }
        public virtual Sys_LeatherType Sys_LeatherType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual ICollection<EXP_PIItemColor> EXP_PIItemColor { get; set; }
    }
}
