//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_BankLoan
    {
        public long BankLoanID { get; set; }
        public string BankLoanNo { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> LoanHead { get; set; }
        public Nullable<decimal> LoanLimit { get; set; }
        public string RefACNo { get; set; }
        public string RefACName { get; set; }
        public Nullable<byte> LoanCurrency { get; set; }
        public string InterestCategory { get; set; }
        public Nullable<System.DateTime> LoanReceiveDate { get; set; }
        public Nullable<decimal> LoanAmt { get; set; }
        public Nullable<decimal> InterestPercent { get; set; }
        public Nullable<decimal> InterestAmt { get; set; }
        public Nullable<decimal> AmountToReturn { get; set; }
        public Nullable<decimal> InterestReturned { get; set; }
        public Nullable<decimal> PrincipleReturned { get; set; }
        public Nullable<decimal> ReturnedAmt { get; set; }
        public Nullable<decimal> InterestBalance { get; set; }
        public Nullable<decimal> PrincipleBalance { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ExchangeAmount { get; set; }
        public Nullable<long> CIID { get; set; }
        public string Remarks { get; set; }
        public string RunningStatus { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckNote { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual User User { get; set; }
        public virtual Sys_Bank Sys_Bank { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual User User1 { get; set; }
        public virtual EXP_CI EXP_CI { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
    }
}
