//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_BankVoucher
    {
        public EXP_BankVoucher()
        {
            this.EXP_BankVoucherDtl = new HashSet<EXP_BankVoucherDtl>();
        }
    
        public long BVID { get; set; }
        public string BVNo { get; set; }
        public string RefBVNo { get; set; }
        public Nullable<System.DateTime> BVDate { get; set; }
        public string BVType { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string ACNo { get; set; }
        public string ACName { get; set; }
        public Nullable<long> CIID { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckNote { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string Remarks { get; set; }
    
        public virtual User User { get; set; }
        public virtual Sys_Bank Sys_Bank { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual User User1 { get; set; }
        public virtual EXP_CI EXP_CI { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<EXP_BankVoucherDtl> EXP_BankVoucherDtl { get; set; }
    }
}
