//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_LCOpening
    {
        public EXP_LCOpening()
        {
            this.EXP_CIPI = new HashSet<EXP_CIPI>();
            this.EXP_BankDebitVoucher = new HashSet<EXP_BankDebitVoucher>();
            this.EXP_ExportForm = new HashSet<EXP_ExportForm>();
            this.EXP_LCRetirement = new HashSet<EXP_LCRetirement>();
            this.EXP_FreightBill = new HashSet<EXP_FreightBill>();
            this.EXP_PLPI = new HashSet<EXP_PLPI>();
        }
    
        public long LCID { get; set; }
        public string LCNo { get; set; }
        public string RefLCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public decimal LCAmount { get; set; }
        public byte LCCurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ExpiryPlace { get; set; }
        public Nullable<int> NNDSendingTime { get; set; }
        public string LCANo { get; set; }
        public string IRCNo { get; set; }
        public string VatRegNo { get; set; }
        public string TINNo { get; set; }
        public string BINNo { get; set; }
        public string ICNNo { get; set; }
        public Nullable<System.DateTime> ICNDate { get; set; }
        public Nullable<System.DateTime> LastShipmentDate { get; set; }
        public Nullable<int> LCOpeningBank { get; set; }
        public Nullable<int> AdvisingBank { get; set; }
        public Nullable<int> Beneficiary { get; set; }
        public Nullable<int> BeneficiaryAddressID { get; set; }
        public Nullable<long> PIID { get; set; }
        public string LCReviceNo { get; set; }
        public Nullable<System.DateTime> LCReviceDate { get; set; }
        public string RunningStatus { get; set; }
        public string LCState { get; set; }
        public string LCStatus { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<EXP_CIPI> EXP_CIPI { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual Sys_BuyerAddress Sys_BuyerAddress { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual Sys_Branch Sys_Branch1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual EXP_LeatherPI EXP_LeatherPI { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<EXP_BankDebitVoucher> EXP_BankDebitVoucher { get; set; }
        public virtual ICollection<EXP_ExportForm> EXP_ExportForm { get; set; }
        public virtual ICollection<EXP_LCRetirement> EXP_LCRetirement { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Sys_SupplierAddress Sys_SupplierAddress { get; set; }
        public virtual ICollection<EXP_FreightBill> EXP_FreightBill { get; set; }
        public virtual ICollection<EXP_PLPI> EXP_PLPI { get; set; }
    }
}
