//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_CIPI
    {
        public EXP_CIPI()
        {
            this.EXP_CIPIItem = new HashSet<EXP_CIPIItem>();
        }
    
        public long CIPIID { get; set; }
        public Nullable<long> CIID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> LCID { get; set; }
        public string PIStatus { get; set; }
        public Nullable<decimal> PIAmount { get; set; }
        public Nullable<byte> PICurrency { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public string RecordStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> PIFootQty { get; set; }
        public Nullable<decimal> PIFootUnitPrice { get; set; }
        public Nullable<decimal> PIFootTotalPrice { get; set; }
        public Nullable<decimal> PIMeterQty { get; set; }
        public Nullable<decimal> PIMeterUnitPrice { get; set; }
        public Nullable<decimal> PIMeterTotalPrice { get; set; }
    
        public virtual EXP_CI EXP_CI { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual EXP_LCOpening EXP_LCOpening { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual EXP_LeatherPI EXP_LeatherPI { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<EXP_CIPIItem> EXP_CIPIItem { get; set; }
    }
}
