//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_LeatherPI
    {
        public EXP_LeatherPI()
        {
            this.EXP_CIPI = new HashSet<EXP_CIPI>();
            this.EXP_LCOpening = new HashSet<EXP_LCOpening>();
            this.EXP_BankDebitVoucher = new HashSet<EXP_BankDebitVoucher>();
            this.EXP_ExportForm = new HashSet<EXP_ExportForm>();
            this.EXP_FreightBill = new HashSet<EXP_FreightBill>();
            this.EXP_PLPI = new HashSet<EXP_PLPI>();
            this.EXP_PIItem = new HashSet<EXP_PIItem>();
            this.EXP_AgentCommissionBuyerCI = new HashSet<EXP_AgentCommissionBuyerCI>();
        }
    
        public long PIID { get; set; }
        public string PINo { get; set; }
        public Nullable<System.DateTime> PIDate { get; set; }
        public string PICategory { get; set; }
        public Nullable<long> BuyerOrderID { get; set; }
        public Nullable<System.DateTime> PIIssueDate { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> LocalAgent { get; set; }
        public Nullable<int> ForeignAgent { get; set; }
        public Nullable<int> PIBeneficiary { get; set; }
        public Nullable<int> BeneficiaryAddressID { get; set; }
        public string PINotify { get; set; }
        public string PIConsignee { get; set; }
        public Nullable<byte> PICurrency { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public string PaymentTerm { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentNote { get; set; }
        public string DeferredDays { get; set; }
        public Nullable<int> CountryOforigin { get; set; }
        public Nullable<int> BeneficiaryBank { get; set; }
        public string DeliveryTerm { get; set; }
        public string DeliveryMode { get; set; }
        public Nullable<int> PortofLoading { get; set; }
        public Nullable<int> PortofDischarge { get; set; }
        public string Transshipment { get; set; }
        public string PartialShipment { get; set; }
        public string GoodDelivery { get; set; }
        public string ShippingMark { get; set; }
        public Nullable<int> ExpectedShipmentTime { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryDate { get; set; }
        public Nullable<System.DateTime> ActualDeliveryDate { get; set; }
        public string Packing { get; set; }
        public string PreShipmentIns { get; set; }
        public Nullable<int> OfferValidityDays { get; set; }
        public string OfferValidityNote { get; set; }
        public string OfferNote { get; set; }
        public string OtherTerm { get; set; }
        public Nullable<System.DateTime> PIRevisionDate { get; set; }
        public string PIState { get; set; }
        public string PIStatus { get; set; }
        public string RecordStatus { get; set; }
        public string PINote { get; set; }
        public string RunningStatus { get; set; }
        public Nullable<byte> CostIndicator { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string BankAccount { get; set; }
        public string InsuranceTerm { get; set; }
        public string ShipmentNote { get; set; }
        public Nullable<int> BuyerBank { get; set; }
        public string BuyerBankAccount { get; set; }
        public string PriceLevel { get; set; }
        public Nullable<decimal> LocalComPercent { get; set; }
        public Nullable<decimal> ForeignComPercent { get; set; }
    
        public virtual ICollection<EXP_CIPI> EXP_CIPI { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_SupplierAddress Sys_SupplierAddress { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual SLS_BuyerOrder SLS_BuyerOrder { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Country Sys_Country { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_BuyerAgent Sys_BuyerAgent { get; set; }
        public virtual Sys_BuyerAgent Sys_BuyerAgent1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual Sys_Port Sys_Port { get; set; }
        public virtual Sys_Port Sys_Port1 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<EXP_BankDebitVoucher> EXP_BankDebitVoucher { get; set; }
        public virtual ICollection<EXP_ExportForm> EXP_ExportForm { get; set; }
        public virtual ICollection<EXP_FreightBill> EXP_FreightBill { get; set; }
        public virtual Sys_Bank Sys_Bank { get; set; }
        public virtual Sys_Branch Sys_Branch1 { get; set; }
        public virtual ICollection<EXP_PLPI> EXP_PLPI { get; set; }
        public virtual ICollection<EXP_PIItem> EXP_PIItem { get; set; }
        public virtual Sys_Buyer Sys_Buyer1 { get; set; }
        public virtual Sys_Buyer Sys_Buyer2 { get; set; }
        public virtual ICollection<EXP_AgentCommissionBuyerCI> EXP_AgentCommissionBuyerCI { get; set; }
    }
}
