//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_ExportForm
    {
        public long ExportFormID { get; set; }
        public string ExportFormNo { get; set; }
        public string ExportFormRef { get; set; }
        public string ExportFormRef1 { get; set; }
        public string ExportFormRef2 { get; set; }
        public string ExportFormRef3 { get; set; }
        public Nullable<System.DateTime> ExportFormDate4 { get; set; }
        public Nullable<long> LCID { get; set; }
        public Nullable<long> CIID { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> PLID { get; set; }
        public string Comodity { get; set; }
        public string ComodityCode { get; set; }
        public Nullable<int> DestinationCountry { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> DestinationPort { get; set; }
        public string PortCode { get; set; }
        public Nullable<decimal> PackQTy { get; set; }
        public Nullable<byte> PackUnit { get; set; }
        public string PackUnitCode { get; set; }
        public Nullable<decimal> VolumeQty { get; set; }
        public Nullable<byte> VolumeUnit { get; set; }
        public Nullable<byte> DeclaredCurrency { get; set; }
        public Nullable<decimal> InvoiceValue { get; set; }
        public Nullable<byte> InvoiceCurrency { get; set; }
        public string DeliveryTerm { get; set; }
        public string TermOfSaleNo { get; set; }
        public Nullable<System.DateTime> TermSaleDate { get; set; }
        public Nullable<int> Importer { get; set; }
        public string CarryingVassal { get; set; }
        public string ExportBillDtl { get; set; }
        public Nullable<int> PortOfShipment { get; set; }
        public Nullable<int> LandCustomPort { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<int> Exporter { get; set; }
        public string CCIESNo { get; set; }
        public Nullable<System.DateTime> CCIESDate { get; set; }
        public string Sector { get; set; }
        public string SectorCode { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> DealerID { get; set; }
    
        public virtual EXP_CI EXP_CI { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Country Sys_Country { get; set; }
        public virtual Sys_Port Sys_Port { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual Sys_Buyer Sys_Buyer1 { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual Sys_Port Sys_Port1 { get; set; }
        public virtual EXP_LCOpening EXP_LCOpening { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual EXP_LeatherPI EXP_LeatherPI { get; set; }
        public virtual EXP_PackingList EXP_PackingList { get; set; }
        public virtual Sys_Port Sys_Port2 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
    }
}
