//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_TransportChallan
    {
        public EXP_TransportChallan()
        {
            this.EXP_TransportChallanCI = new HashSet<EXP_TransportChallanCI>();
        }
    
        public long TransportChallanID { get; set; }
        public string TransportChallanNo { get; set; }
        public string TransportChallanRef { get; set; }
        public Nullable<System.DateTime> TransportChallanDate { get; set; }
        public string TransportChallanNote { get; set; }
        public Nullable<long> DeliverChallanID { get; set; }
        public string Sender { get; set; }
        public string SenderAddress { get; set; }
        public string Receiver { get; set; }
        public string ReceverAddress { get; set; }
        public string DeliveryFrom { get; set; }
        public string DEliveryTo { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmeDate { get; set; }
        public string ConfirmNote { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual EXP_DeliveryChallan EXP_DeliveryChallan { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<EXP_TransportChallanCI> EXP_TransportChallanCI { get; set; }
    }
}
