//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_PLPI
    {
        public EXP_PLPI()
        {
            this.EXP_PLPIItemColor = new HashSet<EXP_PLPIItemColor>();
        }
    
        public long PLPIID { get; set; }
        public Nullable<long> PLID { get; set; }
        public Nullable<decimal> MeterPLPIQty { get; set; }
        public Nullable<decimal> FootPLPIQty { get; set; }
        public Nullable<decimal> PLPINetWeight { get; set; }
        public Nullable<byte> NetWeightUnit { get; set; }
        public Nullable<decimal> PLPIGrossWeight { get; set; }
        public Nullable<byte> GrossWeightUnit { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> PIID { get; set; }
        public Nullable<long> CIID { get; set; }
        public Nullable<long> LCID { get; set; }
        public Nullable<long> BuyerOrderID { get; set; }
        public Nullable<decimal> PLPIPcs { get; set; }
        public Nullable<decimal> PLPISide { get; set; }
    
        public virtual EXP_PackingList EXP_PackingList { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<EXP_PLPIItemColor> EXP_PLPIItemColor { get; set; }
        public virtual EXP_CI EXP_CI { get; set; }
        public virtual EXP_LCOpening EXP_LCOpening { get; set; }
        public virtual EXP_LeatherPI EXP_LeatherPI { get; set; }
        public virtual SLS_BuyerOrder SLS_BuyerOrder { get; set; }
    }
}
