//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_PLPIItemColorBale
    {
        public long PLPIItemColorBaleID { get; set; }
        public string PLPIItemColorBaleNo { get; set; }
        public Nullable<long> PLPIItemColorID { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<decimal> PcsInBale { get; set; }
        public Nullable<decimal> SideInBale { get; set; }
        public Nullable<decimal> MeterPLPIBaleQty { get; set; }
        public Nullable<decimal> FootPLPIBaleQty { get; set; }
        public Nullable<decimal> PLPIBaleNetWeight { get; set; }
        public Nullable<byte> NetWeightUnit { get; set; }
        public Nullable<decimal> PLPIBGrossaleWeight { get; set; }
        public Nullable<byte> GrossBaleWeightUnit { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual Sys_Grade Sys_Grade { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual EXP_PLPIItemColor EXP_PLPIItemColor { get; set; }
    }
}
