//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_BillofLading
    {
        public EXP_BillofLading()
        {
            this.EXP_FreightBill = new HashSet<EXP_FreightBill>();
            this.EXP_BillofLadingContainer = new HashSet<EXP_BillofLadingContainer>();
        }
    
        public long BLID { get; set; }
        public string BLNo { get; set; }
        public Nullable<System.DateTime> BLDate { get; set; }
        public Nullable<long> CIID { get; set; }
        public Nullable<long> PLID { get; set; }
        public Nullable<System.DateTime> ShippedOnBoardDate { get; set; }
        public Nullable<System.DateTime> ExpectedArrivalTime { get; set; }
        public Nullable<int> Shipper { get; set; }
        public string ShipmentMode { get; set; }
        public string VesselName { get; set; }
        public string VoyageNo { get; set; }
        public Nullable<int> TransShipmentPort { get; set; }
        public Nullable<int> ShipmentPort { get; set; }
        public string BLNote { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string RefBLNo { get; set; }
    
        public virtual User User { get; set; }
        public virtual EXP_CI EXP_CI { get; set; }
        public virtual User User1 { get; set; }
        public virtual EXP_PackingList EXP_PackingList { get; set; }
        public virtual User User2 { get; set; }
        public virtual Sys_Port Sys_Port { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual Sys_Port Sys_Port1 { get; set; }
        public virtual ICollection<EXP_FreightBill> EXP_FreightBill { get; set; }
        public virtual ICollection<EXP_BillofLadingContainer> EXP_BillofLadingContainer { get; set; }
    }
}
