//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_FinishLeatherIssue
    {
        public INV_FinishLeatherIssue()
        {
            this.INV_FinishLeatherIssueColor = new HashSet<INV_FinishLeatherIssueColor>();
            this.INV_FinishLeatherIssueItem = new HashSet<INV_FinishLeatherIssueItem>();
            this.INV_FinishLeatherReceiveColor = new HashSet<INV_FinishLeatherReceiveColor>();
            this.INV_FinishLeatherReceiveItem = new HashSet<INV_FinishLeatherReceiveItem>();
            this.INV_FinishLeatherReceiveRef = new HashSet<INV_FinishLeatherReceiveRef>();
        }
    
        public long FinishLeatherIssueID { get; set; }
        public string FinishLeatherIssueNo { get; set; }
        public Nullable<System.DateTime> FinishLeatherIssueDate { get; set; }
        public string IssueCategory { get; set; }
        public string IssueFor { get; set; }
        public Nullable<byte> IssueFrom { get; set; }
        public Nullable<byte> IssueTo { get; set; }
        public Nullable<long> FinishLeatherQCID { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> IssuedBy { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssueNote { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckNote { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string IssueQCStatus { get; set; }
    
        public virtual User User { get; set; }
        public virtual PRD_FinishLeatherQC PRD_FinishLeatherQC { get; set; }
        public virtual User User1 { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual SYS_Store SYS_Store1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueColor> INV_FinishLeatherIssueColor { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueItem> INV_FinishLeatherIssueItem { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveColor> INV_FinishLeatherReceiveColor { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveItem> INV_FinishLeatherReceiveItem { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveRef> INV_FinishLeatherReceiveRef { get; set; }
    }
}
