//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_StockItem
    {
        public long TransectionID { get; set; }
        public byte ItemTypeID { get; set; }
        public byte StoreID { get; set; }
        public byte LeatherType { get; set; }
        public byte LeatherStatus { get; set; }
        public byte UnitID { get; set; }
        public Nullable<decimal> OpeningQty { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }
        public Nullable<decimal> IssueQty { get; set; }
        public Nullable<decimal> ClosingQty { get; set; }
        public Nullable<decimal> RequisitionQty { get; set; }
    
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual Sys_LeatherStatus Sys_LeatherStatus { get; set; }
        public virtual Sys_LeatherType Sys_LeatherType { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
    }
}
