//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class INV_TransRequest
    {
        public INV_TransRequest()
        {
            this.INV_StoreTransItem = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransRequest = new HashSet<INV_StoreTransRequest>();
            this.INV_TransRequestItem = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestRef = new HashSet<INV_TransRequestRef>();
            this.INV_TransRequestRef1 = new HashSet<INV_TransRequestRef>();
        }
    
        public long RequestID { get; set; }
        public string RequestNo { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestCategory { get; set; }
        public string RequestType { get; set; }
        public string RequestFrom { get; set; }
        public string RequestTo { get; set; }
        public string ReturnMethod { get; set; }
        public Nullable<byte> ExpectetReturnTime { get; set; }
        public Nullable<int> RefTransactionID { get; set; }
        public string RefTransactionNo { get; set; }
        public string RefTransactionType { get; set; }
        public Nullable<int> RefLetterID { get; set; }
        public string RefLetterNo { get; set; }
        public string RequestStatus { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckComments { get; set; }
        public Nullable<int> RecommendBy { get; set; }
        public Nullable<System.DateTime> RecommendDate { get; set; }
        public string RecommendComments { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveComments { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string FromSource { get; set; }
        public string ToSource { get; set; }
    
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem { get; set; }
        public virtual ICollection<INV_StoreTransRequest> INV_StoreTransRequest { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem { get; set; }
        public virtual ICollection<INV_TransRequestRef> INV_TransRequestRef { get; set; }
        public virtual ICollection<INV_TransRequestRef> INV_TransRequestRef1 { get; set; }
    }
}
