//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCM_Insurence
    {
        public LCM_Insurence()
        {
            this.LCM_LCFileRecord = new HashSet<LCM_LCFileRecord>();
            this.LCM_LCOpening1 = new HashSet<LCM_LCOpening>();
        }
    
        public int InsuranceID { get; set; }
        public string InsuranceNo { get; set; }
        public int InsuranceCompany { get; set; }
        public Nullable<int> LCID { get; set; }
        public string LCNo { get; set; }
        public string CoverNoteDate { get; set; }
        public string MoneyReceiptNo { get; set; }
        public Nullable<System.DateTime> MoneyReceiptDate { get; set; }
        public string ClauseEndorsement { get; set; }
        public string InsuranceChallanNo { get; set; }
        public Nullable<System.DateTime> InsurancChallanDate { get; set; }
        public string PolicyNo { get; set; }
        public Nullable<System.DateTime> PolicyDate { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<byte> InvouceCurrency { get; set; }
        public Nullable<decimal> IncreasePercent { get; set; }
        public Nullable<decimal> IncreaseAmount { get; set; }
        public Nullable<decimal> SumInsured { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<byte> ExchangeRateCurrency { get; set; }
        public Nullable<decimal> ExchangedSumInsured { get; set; }
        public Nullable<decimal> MarinePremiumPercent { get; set; }
        public Nullable<decimal> MarinePremiumAmount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> WarSRCCPercent { get; set; }
        public Nullable<decimal> WarSRCCPercentAmount { get; set; }
        public Nullable<decimal> NetPremium { get; set; }
        public Nullable<decimal> VatPercent { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> StampDutyRetio { get; set; }
        public Nullable<decimal> StampDutyAmount { get; set; }
        public Nullable<decimal> GrandPremium { get; set; }
        public Nullable<decimal> RefundPercent { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string RevisionNo { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public string RunningStatus { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string CINo { get; set; }
        public Nullable<int> CIID { get; set; }
        public Nullable<int> PIID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual LCM_LCOpening LCM_LCOpening { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual LCM_CommercialInvoice LCM_CommercialInvoice { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord { get; set; }
        public virtual PRQ_ChemicalPI PRQ_ChemicalPI { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening1 { get; set; }
    }
}
