//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCM_CommercialInvoice
    {
        public LCM_CommercialInvoice()
        {
            this.LCM_PackingList = new HashSet<LCM_PackingList>();
            this.PRQ_ChemFrgnPurcRecvPL = new HashSet<PRQ_ChemFrgnPurcRecvPL>();
            this.LCM_CommercialInvoiceItem = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_PackingList1 = new HashSet<LCM_PackingList>();
            this.LCM_BankDebitVoucher = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_BillofLading = new HashSet<LCM_BillofLading>();
            this.LCM_CnfBill = new HashSet<LCM_CnfBill>();
            this.LCM_Insurence = new HashSet<LCM_Insurence>();
            this.LCM_LCFileRecord = new HashSet<LCM_LCFileRecord>();
        }
    
        public int CIID { get; set; }
        public string CINo { get; set; }
        public Nullable<System.DateTime> CIDate { get; set; }
        public Nullable<int> LCID { get; set; }
        public string LCNo { get; set; }
        public string CIStatus { get; set; }
        public Nullable<byte> CICurrency { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public Nullable<byte> CostIndicator { get; set; }
        public string CINote { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual LCM_LCOpening LCM_LCOpening { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<LCM_PackingList> LCM_PackingList { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvPL> PRQ_ChemFrgnPurcRecvPL { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem { get; set; }
        public virtual ICollection<LCM_PackingList> LCM_PackingList1 { get; set; }
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher { get; set; }
        public virtual ICollection<LCM_BillofLading> LCM_BillofLading { get; set; }
        public virtual ICollection<LCM_CnfBill> LCM_CnfBill { get; set; }
        public virtual ICollection<LCM_Insurence> LCM_Insurence { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord { get; set; }
    }
}
