//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCM_LCOpening
    {
        public LCM_LCOpening()
        {
            this.LCM_BankDebitVoucher = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_BillofLading = new HashSet<LCM_BillofLading>();
            this.LCM_CnfBill = new HashSet<LCM_CnfBill>();
            this.LCM_CommercialInvoice = new HashSet<LCM_CommercialInvoice>();
            this.LCM_Insurence = new HashSet<LCM_Insurence>();
            this.LCM_LCRetirement = new HashSet<LCM_LCRetirement>();
            this.LCM_PackingList = new HashSet<LCM_PackingList>();
            this.PRQ_ChemFrgnPurcRecvPL = new HashSet<PRQ_ChemFrgnPurcRecvPL>();
            this.LCM_LCFile = new HashSet<LCM_LCFile>();
            this.LCM_LCFileRecord = new HashSet<LCM_LCFileRecord>();
        }
    
        public int LCID { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public decimal LCAmount { get; set; }
        public byte LCCurrencyID { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ExpiryPlace { get; set; }
        public Nullable<int> NNDSendingTime { get; set; }
        public string LCANo { get; set; }
        public string IRCNo { get; set; }
        public string VatRegNo { get; set; }
        public string TINNo { get; set; }
        public string BINNo { get; set; }
        public string ICNNo { get; set; }
        public Nullable<System.DateTime> ICNDate { get; set; }
        public Nullable<System.DateTime> LastShipmentDate { get; set; }
        public Nullable<int> LCOpeningBank { get; set; }
        public Nullable<int> AdvisingBank { get; set; }
        public Nullable<int> Beneficiary { get; set; }
        public Nullable<int> BeneficiaryAddressID { get; set; }
        public Nullable<int> PIID { get; set; }
        public string PINo { get; set; }
        public string LCReviceNo { get; set; }
        public Nullable<System.DateTime> LCReviceDate { get; set; }
        public string RunningStatus { get; set; }
        public string LCState { get; set; }
        public string LCStatus { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> LCMargin { get; set; }
        public Nullable<int> PresentationDays { get; set; }
        public string ConfirmStatus { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public Nullable<byte> PICurrency { get; set; }
        public string PaymentTerm { get; set; }
        public string PaymentMode { get; set; }
        public string DeferredDays { get; set; }
        public Nullable<int> CountryOforigin { get; set; }
        public Nullable<int> BeneficiaryBank { get; set; }
        public string DeliveryTerm { get; set; }
        public string DeliveryMode { get; set; }
        public Nullable<int> PortofLoading { get; set; }
        public Nullable<int> PortofDischarge { get; set; }
        public string Transshipment { get; set; }
        public string PartialShipment { get; set; }
        public string GoodDelivery { get; set; }
        public string ShippingMark { get; set; }
        public Nullable<int> ExpectedShipmentTime { get; set; }
        public string Packing { get; set; }
        public string PreShipmentIns { get; set; }
        public Nullable<int> OfferValidityDays { get; set; }
    
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher { get; set; }
        public virtual ICollection<LCM_BillofLading> LCM_BillofLading { get; set; }
        public virtual ICollection<LCM_CnfBill> LCM_CnfBill { get; set; }
        public virtual ICollection<LCM_CommercialInvoice> LCM_CommercialInvoice { get; set; }
        public virtual ICollection<LCM_Insurence> LCM_Insurence { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Sys_SupplierAddress Sys_SupplierAddress { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual Sys_Branch Sys_Branch1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual PRQ_ChemicalPI PRQ_ChemicalPI { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<LCM_LCRetirement> LCM_LCRetirement { get; set; }
        public virtual ICollection<LCM_PackingList> LCM_PackingList { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvPL> PRQ_ChemFrgnPurcRecvPL { get; set; }
        public virtual ICollection<LCM_LCFile> LCM_LCFile { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord { get; set; }
        public virtual LCM_Insurence LCM_Insurence1 { get; set; }
        public virtual Sys_Bank Sys_Bank { get; set; }
        public virtual Sys_Country Sys_Country { get; set; }
        public virtual Sys_Currency Sys_Currency2 { get; set; }
        public virtual Sys_Port Sys_Port { get; set; }
        public virtual Sys_Port Sys_Port1 { get; set; }
        public virtual Sys_Branch Sys_Branch11 { get; set; }
    }
}
