//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCM_BankDebitVoucher
    {
        public LCM_BankDebitVoucher()
        {
            this.LCM_LCFileRecord = new HashSet<LCM_LCFileRecord>();
        }
    
        public int BDVID { get; set; }
        public string BDVNo { get; set; }
        public Nullable<System.DateTime> BDVDate { get; set; }
        public Nullable<byte> BDVCurrency { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> LCID { get; set; }
        public string LCNo { get; set; }
        public Nullable<decimal> LCMargin { get; set; }
        public Nullable<decimal> CommissionAmt { get; set; }
        public Nullable<decimal> PostageAmt { get; set; }
        public Nullable<decimal> SwiftCharge { get; set; }
        public Nullable<decimal> SourceTaxAmt { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> StationaryExpense { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ExchangeAmount { get; set; }
        public string Remarks { get; set; }
        public string RunningStatus { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string CINo { get; set; }
        public Nullable<int> CIID { get; set; }
        public Nullable<decimal> LCAmt { get; set; }
        public Nullable<decimal> VatOnSwift { get; set; }
        public Nullable<decimal> InsuranceCost { get; set; }
        public string AccountNo { get; set; }
        public Nullable<decimal> OpeningStampCharge { get; set; }
    
        public virtual User User { get; set; }
        public virtual Sys_Bank Sys_Bank { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual LCM_LCOpening LCM_LCOpening { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual LCM_CommercialInvoice LCM_CommercialInvoice { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord { get; set; }
    }
}
