//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCM_LimInfo
    {
        public LCM_LimInfo()
        {
            this.LCM_LCFileRecord = new HashSet<LCM_LCFileRecord>();
        }
    
        public int LimID { get; set; }
        public string LimNo { get; set; }
        public Nullable<System.DateTime> LimDate { get; set; }
        public Nullable<decimal> LimLimit { get; set; }
        public Nullable<decimal> LimBalance { get; set; }
        public Nullable<int> LimBankID { get; set; }
        public Nullable<int> LimBranchID { get; set; }
        public Nullable<int> LCID { get; set; }
        public string LCNo { get; set; }
        public Nullable<decimal> LoanAmount { get; set; }
        public Nullable<decimal> InterestPersent { get; set; }
        public Nullable<decimal> InterestAmount { get; set; }
        public Nullable<decimal> AmountToBePaid { get; set; }
        public Nullable<int> AdjustmentTime { get; set; }
        public Nullable<decimal> OtherCharges { get; set; }
        public Nullable<decimal> AcceptanceCommission { get; set; }
        public Nullable<decimal> HandlingCharge { get; set; }
        public Nullable<decimal> TotalAmountToBePaid { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<byte> LimCurrency { get; set; }
        public Nullable<byte> ExchangeCurrency { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> ExchangeValue { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> LCMarginTransfer { get; set; }
        public Nullable<decimal> LimMarginTrans { get; set; }
        public Nullable<decimal> LimMarginTransPercnt { get; set; }
        public Nullable<System.DateTime> InterestCalcDate { get; set; }
        public Nullable<decimal> CalcInterestAmt { get; set; }
        public Nullable<decimal> ExciseDuty { get; set; }
        public Nullable<decimal> TransCash { get; set; }
        public Nullable<decimal> CalcAmtToPaid { get; set; }
        public Nullable<decimal> LimAdjustDr { get; set; }
        public Nullable<decimal> LimAdjustCr { get; set; }
        public Nullable<decimal> TotalCalcAmtToPaid { get; set; }
    
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Bank Sys_Bank { get; set; }
        public virtual Sys_Branch Sys_Branch { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord { get; set; }
    }
}
