//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_CrustLeatherQC
    {
        public PRD_CrustLeatherQC()
        {
            this.PRD_CrustLeatherQCRef = new HashSet<PRD_CrustLeatherQCRef>();
            this.INV_CrustLeatherIssue = new HashSet<INV_CrustLeatherIssue>();
            this.PRD_CrustLeatherQCItem = new HashSet<PRD_CrustLeatherQCItem>();
            this.PRD_CrustLeatherQCSelection = new HashSet<PRD_CrustLeatherQCSelection>();
        }
    
        public long CrustLeatherQCID { get; set; }
        public string CrustLeatherQCNo { get; set; }
        public Nullable<System.DateTime> CrustLeatherQCDate { get; set; }
        public Nullable<int> CrustLeatherQCBy { get; set; }
        public string QCComments { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public string ConfirmedNote { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckNote { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public string RecordState { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<byte> ProductionFloor { get; set; }
        public Nullable<byte> AfterQCIssueFloor { get; set; }
        public string IssueFloorQCLabel { get; set; }
        public Nullable<byte> AfterQCIssueStore { get; set; }
        public string IssueStoreQCLabel { get; set; }
        public string IssueAfterQC { get; set; }
        public string QCTransactionOf { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual SYS_Store SYS_Store1 { get; set; }
        public virtual SYS_Store SYS_Store2 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCRef> PRD_CrustLeatherQCRef { get; set; }
        public virtual ICollection<INV_CrustLeatherIssue> INV_CrustLeatherIssue { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCItem> PRD_CrustLeatherQCItem { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCSelection> PRD_CrustLeatherQCSelection { get; set; }
    }
}
