//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_WBProductionPurchase
    {
        public PRD_WBProductionPurchase()
        {
            this.PRD_WBProductionChemical = new HashSet<PRD_WBProductionChemical>();
        }
    
        public long WBProductionPurchaseID { get; set; }
        public Nullable<long> WBProductionID { get; set; }
        public Nullable<long> SchedulePurchaseID { get; set; }
        public Nullable<long> ScheduleDateID { get; set; }
        public string ProductionNo { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string MachineNo { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<byte> ItemTypeID { get; set; }
        public Nullable<byte> LeatherTypeID { get; set; }
        public Nullable<byte> LeatherStatusID { get; set; }
        public Nullable<decimal> WBProductionPcs { get; set; }
        public Nullable<decimal> WBProductionSide { get; set; }
        public Nullable<decimal> WBProductionWeight { get; set; }
        public Nullable<byte> WeightUnit { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string ArticleNo { get; set; }
        public string RecipeChallanNo { get; set; }
        public Nullable<int> ProductionProcessID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual PRD_Recipe PRD_Recipe { get; set; }
        public virtual PRD_WBProduction PRD_WBProduction { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical { get; set; }
        public virtual Sys_Article Sys_Article { get; set; }
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual Sys_LeatherStatus Sys_LeatherStatus { get; set; }
        public virtual Sys_LeatherType Sys_LeatherType { get; set; }
        public virtual Sys_Machine Sys_Machine { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_ProductionProces Sys_ProductionProces { get; set; }
        public virtual Prq_Purchase Prq_Purchase { get; set; }
        public virtual PRD_YearMonthScheduleDate PRD_YearMonthScheduleDate { get; set; }
        public virtual PRD_YearMonthSchedulePurchase PRD_YearMonthSchedulePurchase { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
    }
}
