//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_WetBlueProductionStock
    {
        public long TransectionID { get; set; }
        public Nullable<byte> StoreID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public Nullable<long> ChallanID { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<byte> ItemTypeID { get; set; }
        public Nullable<byte> LeatherTypeID { get; set; }
        public Nullable<byte> LeatherStatusID { get; set; }
        public string SelectionStatus { get; set; }
        public Nullable<decimal> OpeningPcs { get; set; }
        public Nullable<decimal> OpeningSide { get; set; }
        public Nullable<decimal> OpeningArea { get; set; }
        public Nullable<decimal> ReceivePcs { get; set; }
        public Nullable<decimal> ReceiveSide { get; set; }
        public Nullable<decimal> ReceiveArea { get; set; }
        public Nullable<decimal> IssuePcs { get; set; }
        public Nullable<decimal> IssueSide { get; set; }
        public Nullable<decimal> IssueArea { get; set; }
        public Nullable<decimal> ClosingProductionkPcs { get; set; }
        public Nullable<decimal> ClosingProductionSide { get; set; }
        public Nullable<decimal> ClosingProductionArea { get; set; }
        public Nullable<byte> AreaUnit { get; set; }
    
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual Sys_LeatherStatus Sys_LeatherStatus { get; set; }
        public virtual Sys_LeatherType Sys_LeatherType { get; set; }
        public virtual Prq_Purchase Prq_Purchase { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Prq_PurchaseChallan Prq_PurchaseChallan { get; set; }
    }
}
