//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_FinishLeatherQCSelection
    {
        public long FNQCSelectionID { get; set; }
        public Nullable<long> FNQCItemID { get; set; }
        public string FNSelectItemNo { get; set; }
        public Nullable<long> FinishLeatherQCRefID { get; set; }
        public Nullable<long> FinishLeatherQCID { get; set; }
        public Nullable<long> ScheduleItemID { get; set; }
        public string ScheduleProductionNo { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<decimal> ProductionPcs { get; set; }
        public Nullable<decimal> ProductionSide { get; set; }
        public Nullable<decimal> ProductionArea { get; set; }
        public Nullable<byte> ProductionAreaUnit { get; set; }
        public Nullable<decimal> QCPassPcs { get; set; }
        public Nullable<decimal> QCPassSide { get; set; }
        public Nullable<decimal> QCPassArea { get; set; }
        public Nullable<byte> QCPassAreaUnit { get; set; }
        public string QCPassRemarks { get; set; }
        public Nullable<decimal> QCFailPcs { get; set; }
        public Nullable<decimal> QCFailSide { get; set; }
        public Nullable<decimal> QCFailArea { get; set; }
        public Nullable<byte> QCFailAreaUnit { get; set; }
        public string QCFailRemarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string GradeRange { get; set; }
    
        public virtual PRD_FinishLeatherQC PRD_FinishLeatherQC { get; set; }
        public virtual PRD_FinishLeatherQCItem PRD_FinishLeatherQCItem { get; set; }
        public virtual PRD_FinishLeatherQCRef PRD_FinishLeatherQCRef { get; set; }
        public virtual Sys_Grade Sys_Grade { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual PRD_YearMonthFinishScheduleItem PRD_YearMonthFinishScheduleItem { get; set; }
    }
}
