//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_YearMonthFinishReqDate
    {
        public PRD_YearMonthFinishReqDate()
        {
            this.PRD_FNProduction = new HashSet<PRD_FNProduction>();
            this.PRD_YearMonthFinishReqItem = new HashSet<PRD_YearMonthFinishReqItem>();
            this.PRD_YearMonthFinishScheduleItem = new HashSet<PRD_YearMonthFinishScheduleItem>();
        }
    
        public long RequisitionDateID { get; set; }
        public Nullable<long> ScheduleID { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string RequisitionStatus { get; set; }
        public string Remark { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction { get; set; }
        public virtual User User { get; set; }
        public virtual PRD_YearMonthSchedule PRD_YearMonthSchedule { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItem> PRD_YearMonthFinishReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleItem> PRD_YearMonthFinishScheduleItem { get; set; }
    }
}
