//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_YearMonthFinishReqItem
    {
        public PRD_YearMonthFinishReqItem()
        {
            this.PRD_YearMonthFinishReqItemColor = new HashSet<PRD_YearMonthFinishReqItemColor>();
        }
    
        public long RequisitionItemID { get; set; }
        public Nullable<long> RequisitionDateID { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<long> ScheduleItemID { get; set; }
        public string ScheduleProductionNo { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<long> BuyerOrderID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string ArticleNo { get; set; }
        public string ArticleChallanNo { get; set; }
        public string AvgSize { get; set; }
        public Nullable<byte> AvgSizeUnit { get; set; }
        public string SideDescription { get; set; }
        public string SelectionRange { get; set; }
        public string Thickness { get; set; }
        public Nullable<byte> ThicknessUnit { get; set; }
        public string ThicknessAt { get; set; }
        public Nullable<byte> ItemTypeID { get; set; }
        public Nullable<byte> LeatherTypeID { get; set; }
        public Nullable<byte> LeatherStatusID { get; set; }
        public Nullable<decimal> RequisitionPcs { get; set; }
        public Nullable<decimal> RequisitionSide { get; set; }
        public Nullable<decimal> RequisitionArea { get; set; }
        public Nullable<byte> AreaUnit { get; set; }
        public string Remark { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> ArticleChallanID { get; set; }
    
        public virtual PRD_YearMonthFinishReqDate PRD_YearMonthFinishReqDate { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_Article Sys_Article { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual SLS_BuyerOrder SLS_BuyerOrder { get; set; }
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual Sys_LeatherStatus Sys_LeatherStatus { get; set; }
        public virtual Sys_LeatherType Sys_LeatherType { get; set; }
        public virtual User User { get; set; }
        public virtual PRD_YearMonthFinishScheduleItem PRD_YearMonthFinishScheduleItem { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Unit Sys_Unit2 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItemColor> PRD_YearMonthFinishReqItemColor { get; set; }
        public virtual Sys_ArticleChallan Sys_ArticleChallan { get; set; }
    }
}
