//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_YearMonthCrustReqDate
    {
        public PRD_YearMonthCrustReqDate()
        {
            this.PRD_CLProduction = new HashSet<PRD_CLProduction>();
            this.PRD_YearMonthCrustReqItem = new HashSet<PRD_YearMonthCrustReqItem>();
            this.PRD_YearMonthCrustScheduleItem = new HashSet<PRD_YearMonthCrustScheduleItem>();
        }
    
        public long RequisitionDateID { get; set; }
        public Nullable<long> ScheduleID { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string RequisitionStatus { get; set; }
        public string Remark { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction { get; set; }
        public virtual User User { get; set; }
        public virtual PRD_YearMonthSchedule PRD_YearMonthSchedule { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItem> PRD_YearMonthCrustReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleItem> PRD_YearMonthCrustScheduleItem { get; set; }
    }
}
