//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_CrustLeatherQCRef
    {
        public PRD_CrustLeatherQCRef()
        {
            this.PRD_CrustLeatherQCItem = new HashSet<PRD_CrustLeatherQCItem>();
            this.PRD_CrustLeatherQCSelection = new HashSet<PRD_CrustLeatherQCSelection>();
        }
    
        public long CrustLeatherQCRefID { get; set; }
        public Nullable<long> CrustLeatherQCID { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public string RecordState { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string ProductionNo { get; set; }
        public Nullable<long> ScheduleItemID { get; set; }
        public string ScheduleProductionNo { get; set; }
    
        public virtual PRD_CrustLeatherQC PRD_CrustLeatherQC { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCItem> PRD_CrustLeatherQCItem { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCSelection> PRD_CrustLeatherQCSelection { get; set; }
        public virtual PRD_YearMonthCrustScheduleItem PRD_YearMonthCrustScheduleItem { get; set; }
    }
}
