//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_WBSellectionIssueGrade
    {
        public long WBSIssueGradeID { get; set; }
        public string WBSIssueGradeNo { get; set; }
        public Nullable<long> WBSelectionGradeID { get; set; }
        public string WBSelectItemNo { get; set; }
        public Nullable<short> GradeID { get; set; }
        public Nullable<decimal> GradeQty { get; set; }
        public Nullable<decimal> GradeSide { get; set; }
        public Nullable<decimal> GradeArea { get; set; }
        public Nullable<byte> AreaUnitID { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> WBSIssueItemID { get; set; }
        public Nullable<byte> SizeID { get; set; }
        public string SizeQtyRef { get; set; }
    
        public virtual PRD_WBSelectionGrade PRD_WBSelectionGrade { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_Grade Sys_Grade { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual PRD_WBSellectionIssueItem PRD_WBSellectionIssueItem { get; set; }
        public virtual Sys_Size Sys_Size { get; set; }
    }
}
