//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_YearMonthSchedule
    {
        public PRD_YearMonthSchedule()
        {
            this.PRD_CLProduction = new HashSet<PRD_CLProduction>();
            this.PRD_YearMonthCrustReqDate = new HashSet<PRD_YearMonthCrustReqDate>();
            this.PRD_YearMonthScheduleDate = new HashSet<PRD_YearMonthScheduleDate>();
            this.PRD_FNProduction = new HashSet<PRD_FNProduction>();
            this.PRD_YearMonthFinishReqDate = new HashSet<PRD_YearMonthFinishReqDate>();
            this.PRD_YearMonthCrustScheduleItem = new HashSet<PRD_YearMonthCrustScheduleItem>();
            this.PRD_YearMonthFinishScheduleItem = new HashSet<PRD_YearMonthFinishScheduleItem>();
        }
    
        public long ScheduleID { get; set; }
        public string ScheduleNo { get; set; }
        public Nullable<long> YearMonID { get; set; }
        public Nullable<System.DateTime> PrepareDate { get; set; }
        public string ScheduleStatus { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckComments { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ProductionProcessID { get; set; }
    
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction { get; set; }
        public virtual PRD_YearMonth PRD_YearMonth { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqDate> PRD_YearMonthCrustReqDate { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual Sys_ProductionProces Sys_ProductionProces { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<PRD_YearMonthScheduleDate> PRD_YearMonthScheduleDate { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqDate> PRD_YearMonthFinishReqDate { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleItem> PRD_YearMonthCrustScheduleItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleItem> PRD_YearMonthFinishScheduleItem { get; set; }
    }
}
