//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_WBProductionChemical
    {
        public long WBProdChemicalID { get; set; }
        public Nullable<long> WBProductionPurchaseID { get; set; }
        public Nullable<long> WBProductionID { get; set; }
        public Nullable<long> SchedulePurchaseID { get; set; }
        public Nullable<int> RequisitionID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> RequiredQty { get; set; }
        public Nullable<byte> RequiredUnitID { get; set; }
        public Nullable<byte> UsePackSize { get; set; }
        public Nullable<byte> UseSizeUnit { get; set; }
        public Nullable<int> UsePackQty { get; set; }
        public Nullable<decimal> UseQty { get; set; }
        public Nullable<byte> UseUnitID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string ItemSource { get; set; }
        public string CalculationBase { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual PRD_ChemProdReq PRD_ChemProdReq { get; set; }
        public virtual PRD_Recipe PRD_Recipe { get; set; }
        public virtual PRD_WBProduction PRD_WBProduction { get; set; }
        public virtual Sys_ChemicalItem Sys_ChemicalItem { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual PRD_YearMonthSchedulePurchase PRD_YearMonthSchedulePurchase { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Supplier Sys_Supplier1 { get; set; }
        public virtual Sys_Size Sys_Size { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual Sys_Unit Sys_Unit2 { get; set; }
        public virtual PRD_WBProductionPurchase PRD_WBProductionPurchase { get; set; }
    }
}
