//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_YearMonthFinishScheduleItem
    {
        public PRD_YearMonthFinishScheduleItem()
        {
            this.PRD_FinishLeatherQCItem = new HashSet<PRD_FinishLeatherQCItem>();
            this.PRD_FinishLeatherQCRef = new HashSet<PRD_FinishLeatherQCRef>();
            this.PRD_FinishLeatherQCSelection = new HashSet<PRD_FinishLeatherQCSelection>();
            this.PRD_FNProduction = new HashSet<PRD_FNProduction>();
            this.PRD_YearMonthFinishReqItem = new HashSet<PRD_YearMonthFinishReqItem>();
            this.PRD_YearMonthFinishScheduleColor = new HashSet<PRD_YearMonthFinishScheduleColor>();
            this.PRD_YearMonthFinishScheduleDrum = new HashSet<PRD_YearMonthFinishScheduleDrum>();
        }
    
        public long ScheduleItemID { get; set; }
        public string ScheduleProductionNo { get; set; }
        public Nullable<long> ScheduleDateID { get; set; }
        public Nullable<long> RequisitionDateID { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<long> ScheduleID { get; set; }
        public Nullable<long> YearMonID { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<long> BuyerOrderID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string ArticleNo { get; set; }
        public string ArticleChallanNo { get; set; }
        public string AvgSize { get; set; }
        public Nullable<byte> AvgSizeUnit { get; set; }
        public string SelectionRange { get; set; }
        public string SideDescription { get; set; }
        public string Thickness { get; set; }
        public Nullable<byte> ThicknessUnit { get; set; }
        public string ThicknessAt { get; set; }
        public Nullable<byte> ItemTypeID { get; set; }
        public Nullable<byte> LeatherTypeID { get; set; }
        public Nullable<byte> LeatherStatusID { get; set; }
        public Nullable<decimal> SchedulePcs { get; set; }
        public Nullable<decimal> ScheduleSide { get; set; }
        public Nullable<decimal> ScheduleArea { get; set; }
        public Nullable<byte> ScheduleAreaUnit { get; set; }
        public Nullable<decimal> ScheduleWeight { get; set; }
        public Nullable<byte> ScheduleWeightUnit { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> ArticleChallanID { get; set; }
    
        public virtual ICollection<PRD_FinishLeatherQCItem> PRD_FinishLeatherQCItem { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCRef> PRD_FinishLeatherQCRef { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCSelection> PRD_FinishLeatherQCSelection { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction { get; set; }
        public virtual PRD_YearMonth PRD_YearMonth { get; set; }
        public virtual PRD_YearMonthFinishReqDate PRD_YearMonthFinishReqDate { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItem> PRD_YearMonthFinishReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleColor> PRD_YearMonthFinishScheduleColor { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleDrum> PRD_YearMonthFinishScheduleDrum { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual SLS_BuyerOrder SLS_BuyerOrder { get; set; }
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual Sys_LeatherStatus Sys_LeatherStatus { get; set; }
        public virtual Sys_LeatherType Sys_LeatherType { get; set; }
        public virtual User User { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
        public virtual PRD_YearMonthScheduleDate PRD_YearMonthScheduleDate { get; set; }
        public virtual PRD_YearMonthSchedule PRD_YearMonthSchedule { get; set; }
        public virtual Sys_Unit Sys_Unit2 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Unit Sys_Unit3 { get; set; }
        public virtual Sys_ArticleChallan Sys_ArticleChallan { get; set; }
    }
}
