//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRD_WBProduction
    {
        public PRD_WBProduction()
        {
            this.PRD_CLProductionChemical = new HashSet<PRD_CLProductionChemical>();
            this.PRD_WBProductionChemical = new HashSet<PRD_WBProductionChemical>();
            this.PRD_WBProductionPurchase = new HashSet<PRD_WBProductionPurchase>();
            this.PRD_FNProductionChemical = new HashSet<PRD_FNProductionChemical>();
        }
    
        public long WBProductionID { get; set; }
        public string WBProductionNo { get; set; }
        public string ProductionFor { get; set; }
        public string ProductionNo { get; set; }
        public Nullable<byte> ProductionFloor { get; set; }
        public string WBProductionInitiator { get; set; }
        public Nullable<long> ScheduleDateID { get; set; }
        public Nullable<System.DateTime> WBProductionStartDate { get; set; }
        public Nullable<System.DateTime> WBProductionEndDate { get; set; }
        public Nullable<decimal> WBProductionPcs { get; set; }
        public Nullable<decimal> WBProductionSide { get; set; }
        public Nullable<decimal> WBProductionWeight { get; set; }
        public Nullable<byte> WBWeightUnit { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public string ArticleNo { get; set; }
        public string RecipeChallanNo { get; set; }
        public Nullable<int> ProductionProcessID { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmeDate { get; set; }
        public string ConfirmeNote { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical { get; set; }
        public virtual PRD_Recipe PRD_Recipe { get; set; }
        public virtual Sys_Article Sys_Article { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual Sys_ProductionProces Sys_ProductionProces { get; set; }
        public virtual PRD_YearMonthScheduleDate PRD_YearMonthScheduleDate { get; set; }
        public virtual User User4 { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical { get; set; }
        public virtual ICollection<PRD_WBProductionPurchase> PRD_WBProductionPurchase { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical { get; set; }
    }
}
