//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prq_PurchaseChallan
    {
        public Prq_PurchaseChallan()
        {
            this.Inv_LeatherIssueItem = new HashSet<Inv_LeatherIssueItem>();
            this.Inv_LeatherStockAdjustItem = new HashSet<Inv_LeatherStockAdjustItem>();
            this.Inv_LeatherTransferReceiveItem = new HashSet<Inv_LeatherTransferReceiveItem>();
            this.Inv_StockSupplier = new HashSet<Inv_StockSupplier>();
            this.INV_WetBlueSelectionStock = new HashSet<INV_WetBlueSelectionStock>();
            this.PRD_WetBlueProductionStock = new HashSet<PRD_WetBlueProductionStock>();
            this.Prq_PreGradeChallan = new HashSet<Prq_PreGradeChallan>();
            this.Prq_PurchaseChallanItem = new HashSet<Prq_PurchaseChallanItem>();
            this.Prq_SupplierBillChallan = new HashSet<Prq_SupplierBillChallan>();
        }
    
        public long ChallanID { get; set; }
        public string ChallanNo { get; set; }
        public long PurchaseID { get; set; }
        public int SourceID { get; set; }
        public int LocationID { get; set; }
        public byte ReceiveStore { get; set; }
        public string ChallanCategory { get; set; }
        public string ChallanNote { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public string RecordStatus { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<Inv_LeatherIssueItem> Inv_LeatherIssueItem { get; set; }
        public virtual ICollection<Inv_LeatherStockAdjustItem> Inv_LeatherStockAdjustItem { get; set; }
        public virtual ICollection<Inv_LeatherTransferReceiveItem> Inv_LeatherTransferReceiveItem { get; set; }
        public virtual ICollection<Inv_StockSupplier> Inv_StockSupplier { get; set; }
        public virtual ICollection<INV_WetBlueSelectionStock> INV_WetBlueSelectionStock { get; set; }
        public virtual ICollection<PRD_WetBlueProductionStock> PRD_WetBlueProductionStock { get; set; }
        public virtual ICollection<Prq_PreGradeChallan> Prq_PreGradeChallan { get; set; }
        public virtual Prq_Purchase Prq_Purchase { get; set; }
        public virtual Sys_Location Sys_Location { get; set; }
        public virtual Sys_Source Sys_Source { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual ICollection<Prq_PurchaseChallanItem> Prq_PurchaseChallanItem { get; set; }
        public virtual ICollection<Prq_SupplierBillChallan> Prq_SupplierBillChallan { get; set; }
    }
}
