//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRQ_ChemLocalPurcBill
    {
        public PRQ_ChemLocalPurcBill()
        {
            this.PRQ_ChemBillPymtReference = new HashSet<PRQ_ChemBillPymtReference>();
            this.PRQ_ChemLocalPurcBillRef = new HashSet<PRQ_ChemLocalPurcBillRef>();
        }
    
        public long BillID { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> SupplierAddressID { get; set; }
        public string PurchaseYear { get; set; }
        public string SupplierBillNo { get; set; }
        public Nullable<System.DateTime> SupBillDate { get; set; }
        public string BillCategory { get; set; }
        public string BillType { get; set; }
        public Nullable<decimal> BillAmt { get; set; }
        public string BillStatus { get; set; }
        public Nullable<byte> Currency { get; set; }
        public Nullable<decimal> VatAmt { get; set; }
        public Nullable<decimal> ApprovedAmt { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> PayableAmt { get; set; }
        public Nullable<byte> ExchangCurrency { get; set; }
        public Nullable<decimal> ExchangRate { get; set; }
        public Nullable<decimal> ExchangValue { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckComments { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalComments { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<PRQ_ChemBillPymtReference> PRQ_ChemBillPymtReference { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual Sys_Currency Sys_Currency1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual Sys_SupplierAddress Sys_SupplierAddress { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillRef> PRQ_ChemLocalPurcBillRef { get; set; }
    }
}
