//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prq_PurchaseYearPeriodItemAudit
    {
        public long RevisieID { get; set; }
        public string RevisionReason { get; set; }
        public byte RevisionNo { get; set; }
        public int PeriodItemID { get; set; }
        public int PeriodID { get; set; }
        public byte ItemTypeID { get; set; }
        public byte LeatherType { get; set; }
        public byte LeatherStatus { get; set; }
        public byte SizeID { get; set; }
        public Nullable<long> TargetQuantity { get; set; }
        public byte UnitID { get; set; }
        public Nullable<decimal> TargetValue { get; set; }
        public byte CurrencyID { get; set; }
        public string RecordStatus { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public string IPAddress { get; set; }
    }
}
