//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRQ_ChemFrgnPurcOrdr
    {
        public PRQ_ChemFrgnPurcOrdr()
        {
            this.PRQ_ChemFrgnPurcOrdrItem = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcOrdrRqsn = new HashSet<PRQ_ChemFrgnPurcOrdrRqsn>();
            this.PRQ_ChemicalPI = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemLocalPurcBillRef = new HashSet<PRQ_ChemLocalPurcBillRef>();
            this.PRQ_ChemLocalPurcRecvPO = new HashSet<PRQ_ChemLocalPurcRecvPO>();
        }
    
        public int OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderCategory { get; set; }
        public string OrderType { get; set; }
        public Nullable<byte> OrderFrom { get; set; }
        public string OrderTo { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> LocalAgent { get; set; }
        public Nullable<int> ForeignAgent { get; set; }
        public string CostIndicator { get; set; }
        public string OrderNote { get; set; }
        public string OrderStatus { get; set; }
        public string OrderState { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Sys_Supplier Sys_Supplier1 { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual Sys_Supplier Sys_Supplier2 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrRqsn> PRQ_ChemFrgnPurcOrdrRqsn { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillRef> PRQ_ChemLocalPurcBillRef { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvPO> PRQ_ChemLocalPurcRecvPO { get; set; }
    }
}
