//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRQ_ChemFrgnPurcRecv
    {
        public PRQ_ChemFrgnPurcRecv()
        {
            this.PRQ_ChemFrgnPurcRecvChallan = new HashSet<PRQ_ChemFrgnPurcRecvChallan>();
            this.PRQ_ChemFrgnPurcRecvItem = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemFrgnPurcRecvPL = new HashSet<PRQ_ChemFrgnPurcRecvPL>();
        }
    
        public int ReceiveID { get; set; }
        public string ReceiveNo { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string ReceiveCategory { get; set; }
        public string ReceiveType { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> SupplierAddressID { get; set; }
        public byte ReceiveStore { get; set; }
        public string RecordStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckComments { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual User User3 { get; set; }
        public virtual Sys_SupplierAddress Sys_SupplierAddress { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvChallan> PRQ_ChemFrgnPurcRecvChallan { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvPL> PRQ_ChemFrgnPurcRecvPL { get; set; }
    }
}
