//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prq_PurchaseYearPeriod
    {
        public Prq_PurchaseYearPeriod()
        {
            this.Prq_PurchaseYearPeriodItem = new HashSet<Prq_PurchaseYearPeriodItem>();
        }
    
        public int PeriodID { get; set; }
        public int YearID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string RecordStatus { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Prq_PurchaseYearTarget Prq_PurchaseYearTarget { get; set; }
        public virtual ICollection<Prq_PurchaseYearPeriodItem> Prq_PurchaseYearPeriodItem { get; set; }
    }
}
