//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prq_SupplierBill
    {
        public Prq_SupplierBill()
        {
            this.Prq_BillPaymentReference = new HashSet<Prq_BillPaymentReference>();
            this.Prq_SupplierBillChallan = new HashSet<Prq_SupplierBillChallan>();
            this.Prq_SupplierBillItem = new HashSet<Prq_SupplierBillItem>();
        }
    
        public long SupplierBillID { get; set; }
        public int SupplierID { get; set; }
        public int SupplierAddressID { get; set; }
        public string PurchaseYear { get; set; }
        public string SupplierBillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillCategory { get; set; }
        public string BillType { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> AvgPrice { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<decimal> TotalRejectQty { get; set; }
        public Nullable<decimal> ApprovedPrice { get; set; }
        public Nullable<decimal> ApprovedAmt { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> DiscountAmt { get; set; }
        public Nullable<decimal> PayableAmt { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckComment { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveComment { get; set; }
        public string IPAddress { get; set; }
        public Nullable<long> PurchaseID { get; set; }
        public string SupplierBillRefNo { get; set; }
    
        public virtual ICollection<Prq_BillPaymentReference> Prq_BillPaymentReference { get; set; }
        public virtual Prq_Purchase Prq_Purchase { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual Sys_SupplierAddress Sys_SupplierAddress { get; set; }
        public virtual ICollection<Prq_SupplierBillChallan> Prq_SupplierBillChallan { get; set; }
        public virtual ICollection<Prq_SupplierBillItem> Prq_SupplierBillItem { get; set; }
    }
}
