//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRQ_ChemLocalPurcBillRef
    {
        public PRQ_ChemLocalPurcBillRef()
        {
            this.PRQ_ChemLocalPurcBillItem = new HashSet<PRQ_ChemLocalPurcBillItem>();
        }
    
        public long BillRefID { get; set; }
        public Nullable<long> BillID { get; set; }
        public Nullable<long> ReceiveID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual PRQ_ChemFrgnPurcOrdr PRQ_ChemFrgnPurcOrdr { get; set; }
        public virtual PRQ_ChemLocalPurcBill PRQ_ChemLocalPurcBill { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillItem> PRQ_ChemLocalPurcBillItem { get; set; }
        public virtual User User { get; set; }
        public virtual PRQ_ChemLocalPurcRecv PRQ_ChemLocalPurcRecv { get; set; }
        public virtual User User1 { get; set; }
    }
}
