//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prq_SupplierBillChallan
    {
        public long SupplierBillID { get; set; }
        public long ChallanID { get; set; }
        public string S_ChallanRef { get; set; }
        public string ChallanCategory { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> PurchaseID { get; set; }
    
        public virtual Prq_Purchase Prq_Purchase { get; set; }
        public virtual Prq_SupplierBill Prq_SupplierBill { get; set; }
        public virtual Prq_PurchaseChallan Prq_PurchaseChallan { get; set; }
    }
}
