//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prq_PreGradeChallan
    {
        public long SelectionID { get; set; }
        public long ChallanID { get; set; }
        public long PurchaseID { get; set; }
        public Nullable<decimal> ChallanReceiveQty { get; set; }
        public Nullable<decimal> ChallanSelectionQty { get; set; }
        public string Remarks { get; set; }
        public string RecordStatus { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Prq_PreGradeSelection Prq_PreGradeSelection { get; set; }
        public virtual Prq_PurchaseChallan Prq_PurchaseChallan { get; set; }
    }
}
