//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRQ_ChemLocalPurcRecvPO
    {
        public PRQ_ChemLocalPurcRecvPO()
        {
            this.PRQ_ChemLocalPurcRecvChallan = new HashSet<PRQ_ChemLocalPurcRecvChallan>();
            this.PRQ_ChemLocalPurcRecvItem = new HashSet<PRQ_ChemLocalPurcRecvItem>();
        }
    
        public long POReceiveID { get; set; }
        public Nullable<long> ReceiveID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string OrderNo { get; set; }
        public string Remark { get; set; }
        public string CheckedBy { get; set; }
        public string CheckComments { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual PRQ_ChemFrgnPurcOrdr PRQ_ChemFrgnPurcOrdr { get; set; }
        public virtual PRQ_ChemLocalPurcRecv PRQ_ChemLocalPurcRecv { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvChallan> PRQ_ChemLocalPurcRecvChallan { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
