//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRQ_ChemPurcReq
    {
        public PRQ_ChemPurcReq()
        {
            this.PRQ_ChemFrgnPurcOrdrItem = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcOrdrRqsn = new HashSet<PRQ_ChemFrgnPurcOrdrRqsn>();
            this.PRQ_ChemPurcReqItem = new HashSet<PRQ_ChemPurcReqItem>();
        }
    
        public int RequisitionID { get; set; }
        public string RequisitionNo { get; set; }
        public string RequisitionCategory { get; set; }
        public string RequisitionType { get; set; }
        public Nullable<byte> RequisitionFrom { get; set; }
        public Nullable<int> RequisitionTo { get; set; }
        public Nullable<byte> RequiredByTime { get; set; }
        public Nullable<int> ReqRaisedBy { get; set; }
        public Nullable<System.DateTime> ReqRaisedOn { get; set; }
        public string RequisitionNote { get; set; }
        public Nullable<int> RecipeFor { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public string ArticleNo { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public string RequisitionStatus { get; set; }
        public string RequisitionState { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalAdvice { get; set; }
        public string ApprovalAdviceNote { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public Nullable<int> PreparedBy { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual PRD_Recipe PRD_Recipe { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrRqsn> PRQ_ChemFrgnPurcOrdrRqsn { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual Sys_ProductionProces Sys_ProductionProces { get; set; }
        public virtual User User4 { get; set; }
        public virtual SYS_Store SYS_Store { get; set; }
        public virtual User User5 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem { get; set; }
    }
}
