//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        public Screen()
        {
            this.Sys_PreDefineValueFor = new HashSet<Sys_PreDefineValueFor>();
            this.AdditionalScreenPermissions = new HashSet<AdditionalScreenPermission>();
            this.MenuItems = new HashSet<MenuItem>();
            this.RoleWiseScreenPermissions = new HashSet<RoleWiseScreenPermission>();
            this.ScreenOperations = new HashSet<ScreenOperation>();
        }
    
        public string ScreenCode { get; set; }
        public string ModuleID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string URL { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string Description { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
    
        public virtual ICollection<Sys_PreDefineValueFor> Sys_PreDefineValueFor { get; set; }
        public virtual ICollection<AdditionalScreenPermission> AdditionalScreenPermissions { get; set; }
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual Module Module { get; set; }
        public virtual ICollection<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }
        public virtual ICollection<ScreenOperation> ScreenOperations { get; set; }
    }
}
