//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLS_BuyerOrder
    {
        public SLS_BuyerOrder()
        {
            this.INV_CLTransferFrom = new HashSet<INV_CLTransferFrom>();
            this.INV_CLTransferTo = new HashSet<INV_CLTransferTo>();
            this.INV_CrustBuyerStock = new HashSet<INV_CrustBuyerStock>();
            this.INV_CrustQCStock = new HashSet<INV_CrustQCStock>();
            this.INV_CrustLeatherReceiveItem = new HashSet<INV_CrustLeatherReceiveItem>();
            this.PRD_CrustLeatherProductionStock = new HashSet<PRD_CrustLeatherProductionStock>();
            this.INV_FinishBuyerStock = new HashSet<INV_FinishBuyerStock>();
            this.INV_FinishLeatherIssueItem = new HashSet<INV_FinishLeatherIssueItem>();
            this.INV_FinishLeatherReceiveItem = new HashSet<INV_FinishLeatherReceiveItem>();
            this.INV_FNTransferFrom = new HashSet<INV_FNTransferFrom>();
            this.INV_FNTransferTo = new HashSet<INV_FNTransferTo>();
            this.PRD_FinishLeatherQCItem = new HashSet<PRD_FinishLeatherQCItem>();
            this.PRD_FinishLeatherProductionStock = new HashSet<PRD_FinishLeatherProductionStock>();
            this.INV_FinishBuyerQCStock = new HashSet<INV_FinishBuyerQCStock>();
            this.INV_FinishOwnQCStock = new HashSet<INV_FinishOwnQCStock>();
            this.EXP_LeatherPI = new HashSet<EXP_LeatherPI>();
            this.PRD_CrustLeatherQCItem = new HashSet<PRD_CrustLeatherQCItem>();
            this.INV_CrustLeatherIssueItem = new HashSet<INV_CrustLeatherIssueItem>();
            this.INV_WetBlueIssueRef = new HashSet<INV_WetBlueIssueRef>();
            this.PRD_CLProductionItem = new HashSet<PRD_CLProductionItem>();
            this.PRD_FNProductionItem = new HashSet<PRD_FNProductionItem>();
            this.PRD_YearMonthCrustReqItem = new HashSet<PRD_YearMonthCrustReqItem>();
            this.PRD_YearMonthCrustScheduleItem = new HashSet<PRD_YearMonthCrustScheduleItem>();
            this.PRD_YearMonthFinishReqItem = new HashSet<PRD_YearMonthFinishReqItem>();
            this.PRD_YearMonthFinishScheduleItem = new HashSet<PRD_YearMonthFinishScheduleItem>();
            this.INV_FinishPackingStock = new HashSet<INV_FinishPackingStock>();
            this.SLS_BuyerOrderDelivery = new HashSet<SLS_BuyerOrderDelivery>();
            this.SLS_BuyerOrderPrice = new HashSet<SLS_BuyerOrderPrice>();
            this.EXP_PLPI = new HashSet<EXP_PLPI>();
            this.SLS_BuyerOrderItem = new HashSet<SLS_BuyerOrderItem>();
            this.SLS_BuyerOrderItemColor = new HashSet<SLS_BuyerOrderItemColor>();
        }
    
        public long BuyerOrderID { get; set; }
        public string BuyerOrderNo { get; set; }
        public Nullable<System.DateTime> BuyerOrderDate { get; set; }
        public string BuyerOrderCategory { get; set; }
        public string BuyerOrderStatus { get; set; }
        public string AcknowledgementStatus { get; set; }
        public Nullable<int> BuyerID { get; set; }
        public Nullable<int> BuyerAddressID { get; set; }
        public Nullable<int> BuyerLocalAgentID { get; set; }
        public Nullable<int> BuyerForeignAgentID { get; set; }
        public string BuyerRef { get; set; }
        public Nullable<System.DateTime> ExpectedShipmentDate { get; set; }
        public Nullable<System.DateTime> ProposedShipmentDate { get; set; }
        public Nullable<System.DateTime> DeliveryLastDate { get; set; }
        public Nullable<System.DateTime> ExpectedProdStartDate { get; set; }
        public string RevisionNo { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public string RecordStatus { get; set; }
        public Nullable<int> CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckNote { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApprovalNote { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string OrderFrom { get; set; }
        public string OrderNo { get; set; }
        public string AcknowledgeNote { get; set; }
        public Nullable<int> AcknowledgedBy { get; set; }
        public Nullable<System.DateTime> AckDate { get; set; }
        public Nullable<byte> OrderCurrency { get; set; }
        public Nullable<decimal> TotalFootQty { get; set; }
        public Nullable<decimal> TotalMeterQty { get; set; }
        public string PriceLevel { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_BuyerAddress Sys_BuyerAddress { get; set; }
        public virtual Sys_BuyerAgent Sys_BuyerAgent { get; set; }
        public virtual Sys_Buyer Sys_Buyer { get; set; }
        public virtual Sys_BuyerAgent Sys_BuyerAgent1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual User User3 { get; set; }
        public virtual User User4 { get; set; }
        public virtual ICollection<INV_CLTransferFrom> INV_CLTransferFrom { get; set; }
        public virtual ICollection<INV_CLTransferTo> INV_CLTransferTo { get; set; }
        public virtual ICollection<INV_CrustBuyerStock> INV_CrustBuyerStock { get; set; }
        public virtual ICollection<INV_CrustQCStock> INV_CrustQCStock { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveItem> INV_CrustLeatherReceiveItem { get; set; }
        public virtual ICollection<PRD_CrustLeatherProductionStock> PRD_CrustLeatherProductionStock { get; set; }
        public virtual ICollection<INV_FinishBuyerStock> INV_FinishBuyerStock { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueItem> INV_FinishLeatherIssueItem { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveItem> INV_FinishLeatherReceiveItem { get; set; }
        public virtual ICollection<INV_FNTransferFrom> INV_FNTransferFrom { get; set; }
        public virtual ICollection<INV_FNTransferTo> INV_FNTransferTo { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCItem> PRD_FinishLeatherQCItem { get; set; }
        public virtual ICollection<PRD_FinishLeatherProductionStock> PRD_FinishLeatherProductionStock { get; set; }
        public virtual ICollection<INV_FinishBuyerQCStock> INV_FinishBuyerQCStock { get; set; }
        public virtual ICollection<INV_FinishOwnQCStock> INV_FinishOwnQCStock { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCItem> PRD_CrustLeatherQCItem { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueItem> INV_CrustLeatherIssueItem { get; set; }
        public virtual Sys_Currency Sys_Currency { get; set; }
        public virtual ICollection<INV_WetBlueIssueRef> INV_WetBlueIssueRef { get; set; }
        public virtual ICollection<PRD_CLProductionItem> PRD_CLProductionItem { get; set; }
        public virtual ICollection<PRD_FNProductionItem> PRD_FNProductionItem { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItem> PRD_YearMonthCrustReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleItem> PRD_YearMonthCrustScheduleItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItem> PRD_YearMonthFinishReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleItem> PRD_YearMonthFinishScheduleItem { get; set; }
        public virtual ICollection<INV_FinishPackingStock> INV_FinishPackingStock { get; set; }
        public virtual ICollection<SLS_BuyerOrderDelivery> SLS_BuyerOrderDelivery { get; set; }
        public virtual ICollection<SLS_BuyerOrderPrice> SLS_BuyerOrderPrice { get; set; }
        public virtual ICollection<EXP_PLPI> EXP_PLPI { get; set; }
        public virtual ICollection<SLS_BuyerOrderItem> SLS_BuyerOrderItem { get; set; }
        public virtual ICollection<SLS_BuyerOrderItemColor> SLS_BuyerOrderItemColor { get; set; }
        public virtual Sys_Buyer Sys_Buyer1 { get; set; }
        public virtual Sys_Buyer Sys_Buyer2 { get; set; }
    }
}
