//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLS_BuyerOrderItemColor
    {
        public long BuyerOrdItemColorID { get; set; }
        public Nullable<long> BuyerOrderID { get; set; }
        public Nullable<long> BuyerOrderItemID { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> ColorQty { get; set; }
        public Nullable<byte> ColorUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<decimal> ColorFootQty { get; set; }
        public Nullable<decimal> SeaFootUnitPrice { get; set; }
        public Nullable<decimal> SeaFootTotalPrice { get; set; }
        public Nullable<decimal> AirFootUnitPrice { get; set; }
        public Nullable<decimal> AirFootTotalPrice { get; set; }
        public Nullable<decimal> RoadFootUnitPrice { get; set; }
        public Nullable<decimal> RoadFootTotalPrice { get; set; }
        public Nullable<decimal> ColorMeterQty { get; set; }
        public Nullable<decimal> SeaMeterUnitPrice { get; set; }
        public Nullable<decimal> SeaMeterTotalPrice { get; set; }
        public Nullable<decimal> AirMeterUnitPrice { get; set; }
        public Nullable<decimal> AirMeterTotalPrice { get; set; }
        public Nullable<decimal> RoadMeterUnitPrice { get; set; }
        public Nullable<decimal> RoadMeterTotalPrice { get; set; }
    
        public virtual SLS_BuyerOrder SLS_BuyerOrder { get; set; }
        public virtual SLS_BuyerOrderItem SLS_BuyerOrderItem { get; set; }
        public virtual Sys_Color Sys_Color { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
