//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLS_BuyerOrderPrice
    {
        public long BuyerOrderPriceID { get; set; }
        public Nullable<long> BuyerOrderID { get; set; }
        public string OrdDeliveryMode { get; set; }
        public string OrdRefDeliverySL { get; set; }
        public Nullable<decimal> OrdAverageUnitPrice { get; set; }
        public string OrdDeliveryModeNote { get; set; }
        public string PIDeliveryMode { get; set; }
        public string PIRefDeliverySL { get; set; }
        public Nullable<decimal> PIAverageUnitPrice { get; set; }
        public string PIDeliveryModeNote { get; set; }
        public Nullable<int> ArticleID { get; set; }
        public Nullable<decimal> ArticleFootQty { get; set; }
        public Nullable<decimal> ArticleFootUnitPrice { get; set; }
        public Nullable<decimal> ArticleFootTotalPrice { get; set; }
        public Nullable<decimal> ArticleMeterQty { get; set; }
        public Nullable<decimal> ArticleMeterUnitPrice { get; set; }
        public Nullable<decimal> ArticleMeterTotalPrice { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<decimal> ColorFootQty { get; set; }
        public Nullable<decimal> ColorFootUnitPrice { get; set; }
        public Nullable<decimal> ColorFootTotalPrice { get; set; }
        public Nullable<decimal> ColorMeterQty { get; set; }
        public Nullable<decimal> ColorMeterUnitPrice { get; set; }
        public Nullable<decimal> ColorMeterTotalPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SLS_BuyerOrder SLS_BuyerOrder { get; set; }
        public virtual Sys_Article Sys_Article { get; set; }
        public virtual Sys_Color Sys_Color { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
