//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ChemicalItem
    {
        public Sys_ChemicalItem()
        {
            this.INV_ChemStockDaily = new HashSet<INV_ChemStockDaily>();
            this.INV_ChemStockItem = new HashSet<INV_ChemStockItem>();
            this.INV_ChemStockSupplier = new HashSet<INV_ChemStockSupplier>();
            this.INV_StoreTransItem = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransItem1 = new HashSet<INV_StoreTransItem>();
            this.INV_TransRequestItem = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestItem1 = new HashSet<INV_TransRequestItem>();
            this.LCM_CommercialInvoiceItem = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_PackingListItem = new HashSet<LCM_PackingListItem>();
            this.PRD_ChemProdReqItem = new HashSet<PRD_ChemProdReqItem>();
            this.PRD_CLProductionChemical = new HashSet<PRD_CLProductionChemical>();
            this.PRD_RecipeItem = new HashSet<PRD_RecipeItem>();
            this.PRD_WBProductionChemical = new HashSet<PRD_WBProductionChemical>();
            this.PRQ_ChemFrgnPurcOrdrItem = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcRecvItem = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemicalPIItem = new HashSet<PRQ_ChemicalPIItem>();
            this.PRQ_ChemLocalPurcBillItem = new HashSet<PRQ_ChemLocalPurcBillItem>();
            this.PRQ_ChemLocalPurcRecvItem = new HashSet<PRQ_ChemLocalPurcRecvItem>();
            this.PRQ_ChemPurcReqItem = new HashSet<PRQ_ChemPurcReqItem>();
            this.PRD_FNProductionChemical = new HashSet<PRD_FNProductionChemical>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string HSCode { get; set; }
        public string ItemCategory { get; set; }
        public Nullable<byte> ItemTypeID { get; set; }
        public Nullable<byte> UnitID { get; set; }
        public Nullable<int> SafetyStock { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ExpiryLimit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<INV_ChemStockDaily> INV_ChemStockDaily { get; set; }
        public virtual ICollection<INV_ChemStockItem> INV_ChemStockItem { get; set; }
        public virtual ICollection<INV_ChemStockSupplier> INV_ChemStockSupplier { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem1 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem1 { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem { get; set; }
        public virtual ICollection<LCM_PackingListItem> LCM_PackingListItem { get; set; }
        public virtual ICollection<PRD_ChemProdReqItem> PRD_ChemProdReqItem { get; set; }
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical { get; set; }
        public virtual ICollection<PRD_RecipeItem> PRD_RecipeItem { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemicalPIItem> PRQ_ChemicalPIItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillItem> PRQ_ChemLocalPurcBillItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem { get; set; }
        public virtual Sys_ItemType Sys_ItemType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical { get; set; }
    }
}
