//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Machine
    {
        public Sys_Machine()
        {
            this.PRD_CLProductionDrum = new HashSet<PRD_CLProductionDrum>();
            this.PRD_WBProductionPurchase = new HashSet<PRD_WBProductionPurchase>();
            this.PRD_YearMonthCrustScheduleDrum = new HashSet<PRD_YearMonthCrustScheduleDrum>();
            this.PRD_YearMonthSchedulePurchase = new HashSet<PRD_YearMonthSchedulePurchase>();
            this.PRD_FNProductionDrum = new HashSet<PRD_FNProductionDrum>();
            this.PRD_YearMonthFinishScheduleDrum = new HashSet<PRD_YearMonthFinishScheduleDrum>();
        }
    
        public int MachineID { get; set; }
        public string MachineNo { get; set; }
        public string MachineCategory { get; set; }
        public string MachineType { get; set; }
        public Nullable<decimal> MachineCapacity { get; set; }
        public Nullable<byte> CapacityUnit { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> ExpiaryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string MachineName { get; set; }
    
        public virtual ICollection<PRD_CLProductionDrum> PRD_CLProductionDrum { get; set; }
        public virtual ICollection<PRD_WBProductionPurchase> PRD_WBProductionPurchase { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleDrum> PRD_YearMonthCrustScheduleDrum { get; set; }
        public virtual ICollection<PRD_YearMonthSchedulePurchase> PRD_YearMonthSchedulePurchase { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PRD_FNProductionDrum> PRD_FNProductionDrum { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleDrum> PRD_YearMonthFinishScheduleDrum { get; set; }
    }
}
