//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PreDefineValueFor
    {
        public Sys_PreDefineValueFor()
        {
            this.Sys_PreDefineValue = new HashSet<Sys_PreDefineValue>();
        }
    
        public int PreDefineValueForID { get; set; }
        public string PreDefineValueFor { get; set; }
        public string ConcernPageID { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<Sys_PreDefineValue> Sys_PreDefineValue { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
