//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Supplier
    {
        public Sys_Supplier()
        {
            this.INV_ChemStockDaily = new HashSet<INV_ChemStockDaily>();
            this.INV_ChemStockItem = new HashSet<INV_ChemStockItem>();
            this.INV_ChemStockSupplier = new HashSet<INV_ChemStockSupplier>();
            this.INV_ChemStockSupplier1 = new HashSet<INV_ChemStockSupplier>();
            this.Inv_LeatherIssueItem = new HashSet<Inv_LeatherIssueItem>();
            this.Inv_LeatherStockAdjustItem = new HashSet<Inv_LeatherStockAdjustItem>();
            this.Inv_LeatherTransferReceiveItem = new HashSet<Inv_LeatherTransferReceiveItem>();
            this.Inv_StockSupplier = new HashSet<Inv_StockSupplier>();
            this.INV_StoreTransItem = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransItem1 = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransItem2 = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransItem3 = new HashSet<INV_StoreTransItem>();
            this.INV_TransRequestItem = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestItem1 = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestItem2 = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestItem3 = new HashSet<INV_TransRequestItem>();
            this.INV_WetBlueIssueItem = new HashSet<INV_WetBlueIssueItem>();
            this.INV_WetBlueSelectionStock = new HashSet<INV_WetBlueSelectionStock>();
            this.INV_WetBlueStockSupplier = new HashSet<INV_WetBlueStockSupplier>();
            this.LCM_CommercialInvoiceItem = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_CommercialInvoiceItem1 = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_LCOpening = new HashSet<LCM_LCOpening>();
            this.LCM_PackingListItem = new HashSet<LCM_PackingListItem>();
            this.LCM_PackingListItem1 = new HashSet<LCM_PackingListItem>();
            this.PRD_ChemProdReqItem = new HashSet<PRD_ChemProdReqItem>();
            this.PRD_ChemProdReqItem1 = new HashSet<PRD_ChemProdReqItem>();
            this.PRD_CLProductionChemical = new HashSet<PRD_CLProductionChemical>();
            this.PRD_CLProductionChemical1 = new HashSet<PRD_CLProductionChemical>();
            this.PRD_WBProductionChemical = new HashSet<PRD_WBProductionChemical>();
            this.PRD_WBProductionChemical1 = new HashSet<PRD_WBProductionChemical>();
            this.PRD_WBProductionPurchase = new HashSet<PRD_WBProductionPurchase>();
            this.PRD_WBSellectionIssueItem = new HashSet<PRD_WBSellectionIssueItem>();
            this.PRD_WetBlueProductionStock = new HashSet<PRD_WetBlueProductionStock>();
            this.PRD_YearMonthSchedulePurchase = new HashSet<PRD_YearMonthSchedulePurchase>();
            this.Prq_BillPayment = new HashSet<Prq_BillPayment>();
            this.Prq_BillRealization = new HashSet<Prq_BillRealization>();
            this.PRQ_ChemBillRealization = new HashSet<PRQ_ChemBillRealization>();
            this.PRQ_ChemFrgnPurcOrdr = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdr1 = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdr2 = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdrItem = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcOrdrItem1 = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcRecv = new HashSet<PRQ_ChemFrgnPurcRecv>();
            this.PRQ_ChemFrgnPurcRecvItem = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemFrgnPurcRecvItem1 = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemicalPI = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPI1 = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPI2 = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPI3 = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPIItem = new HashSet<PRQ_ChemicalPIItem>();
            this.PRQ_ChemicalPIItem1 = new HashSet<PRQ_ChemicalPIItem>();
            this.PRQ_ChemLocalPurcBill = new HashSet<PRQ_ChemLocalPurcBill>();
            this.PRQ_ChemLocalPurcBillItem = new HashSet<PRQ_ChemLocalPurcBillItem>();
            this.PRQ_ChemLocalPurcBillPayment = new HashSet<PRQ_ChemLocalPurcBillPayment>();
            this.PRQ_ChemLocalPurcRecv = new HashSet<PRQ_ChemLocalPurcRecv>();
            this.PRQ_ChemLocalPurcRecvItem = new HashSet<PRQ_ChemLocalPurcRecvItem>();
            this.PRQ_ChemLocalPurcRecvItem1 = new HashSet<PRQ_ChemLocalPurcRecvItem>();
            this.PRQ_ChemPurcReqItem = new HashSet<PRQ_ChemPurcReqItem>();
            this.PRQ_ChemPurcReqItem1 = new HashSet<PRQ_ChemPurcReqItem>();
            this.Prq_PreGradeSelection = new HashSet<Prq_PreGradeSelection>();
            this.Prq_Purchase = new HashSet<Prq_Purchase>();
            this.Prq_SupplierBill = new HashSet<Prq_SupplierBill>();
            this.Sys_SupplierAddress = new HashSet<Sys_SupplierAddress>();
            this.Sys_SupplierAgent = new HashSet<Sys_SupplierAgent>();
            this.Sys_SupplierAgent1 = new HashSet<Sys_SupplierAgent>();
            this.PRD_WBSelectionItem = new HashSet<PRD_WBSelectionItem>();
            this.PRD_FNProductionChemical = new HashSet<PRD_FNProductionChemical>();
            this.PRD_FNProductionChemical1 = new HashSet<PRD_FNProductionChemical>();
            this.EXP_LeatherPI = new HashSet<EXP_LeatherPI>();
            this.EXP_LCOpening = new HashSet<EXP_LCOpening>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCategory { get; set; }
        public string SupplierType { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual ICollection<INV_ChemStockDaily> INV_ChemStockDaily { get; set; }
        public virtual ICollection<INV_ChemStockItem> INV_ChemStockItem { get; set; }
        public virtual ICollection<INV_ChemStockSupplier> INV_ChemStockSupplier { get; set; }
        public virtual ICollection<INV_ChemStockSupplier> INV_ChemStockSupplier1 { get; set; }
        public virtual ICollection<Inv_LeatherIssueItem> Inv_LeatherIssueItem { get; set; }
        public virtual ICollection<Inv_LeatherStockAdjustItem> Inv_LeatherStockAdjustItem { get; set; }
        public virtual ICollection<Inv_LeatherTransferReceiveItem> Inv_LeatherTransferReceiveItem { get; set; }
        public virtual ICollection<Inv_StockSupplier> Inv_StockSupplier { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem1 { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem2 { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem3 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem1 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem2 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem3 { get; set; }
        public virtual ICollection<INV_WetBlueIssueItem> INV_WetBlueIssueItem { get; set; }
        public virtual ICollection<INV_WetBlueSelectionStock> INV_WetBlueSelectionStock { get; set; }
        public virtual ICollection<INV_WetBlueStockSupplier> INV_WetBlueStockSupplier { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem1 { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening { get; set; }
        public virtual ICollection<LCM_PackingListItem> LCM_PackingListItem { get; set; }
        public virtual ICollection<LCM_PackingListItem> LCM_PackingListItem1 { get; set; }
        public virtual ICollection<PRD_ChemProdReqItem> PRD_ChemProdReqItem { get; set; }
        public virtual ICollection<PRD_ChemProdReqItem> PRD_ChemProdReqItem1 { get; set; }
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical { get; set; }
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical1 { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical1 { get; set; }
        public virtual ICollection<PRD_WBProductionPurchase> PRD_WBProductionPurchase { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueItem> PRD_WBSellectionIssueItem { get; set; }
        public virtual ICollection<PRD_WetBlueProductionStock> PRD_WetBlueProductionStock { get; set; }
        public virtual ICollection<PRD_YearMonthSchedulePurchase> PRD_YearMonthSchedulePurchase { get; set; }
        public virtual ICollection<Prq_BillPayment> Prq_BillPayment { get; set; }
        public virtual ICollection<Prq_BillRealization> Prq_BillRealization { get; set; }
        public virtual ICollection<PRQ_ChemBillRealization> PRQ_ChemBillRealization { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr2 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecv> PRQ_ChemFrgnPurcRecv { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem1 { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI1 { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI2 { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI3 { get; set; }
        public virtual ICollection<PRQ_ChemicalPIItem> PRQ_ChemicalPIItem { get; set; }
        public virtual ICollection<PRQ_ChemicalPIItem> PRQ_ChemicalPIItem1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBill> PRQ_ChemLocalPurcBill { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillItem> PRQ_ChemLocalPurcBillItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillPayment> PRQ_ChemLocalPurcBillPayment { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecv> PRQ_ChemLocalPurcRecv { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem1 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem1 { get; set; }
        public virtual ICollection<Prq_PreGradeSelection> Prq_PreGradeSelection { get; set; }
        public virtual ICollection<Prq_Purchase> Prq_Purchase { get; set; }
        public virtual ICollection<Prq_SupplierBill> Prq_SupplierBill { get; set; }
        public virtual Sys_Country Sys_Country { get; set; }
        public virtual ICollection<Sys_SupplierAddress> Sys_SupplierAddress { get; set; }
        public virtual ICollection<Sys_SupplierAgent> Sys_SupplierAgent { get; set; }
        public virtual ICollection<Sys_SupplierAgent> Sys_SupplierAgent1 { get; set; }
        public virtual ICollection<PRD_WBSelectionItem> PRD_WBSelectionItem { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical1 { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening { get; set; }
    }
}
