//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Bank
    {
        public Sys_Bank()
        {
            this.LCM_BankDebitVoucher = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_LimInfo = new HashSet<LCM_LimInfo>();
            this.Sys_Branch = new HashSet<Sys_Branch>();
            this.EXP_BankDebitVoucher = new HashSet<EXP_BankDebitVoucher>();
            this.LCM_LCOpening = new HashSet<LCM_LCOpening>();
            this.PRQ_ChemicalPI = new HashSet<PRQ_ChemicalPI>();
            this.EXP_LeatherPI = new HashSet<EXP_LeatherPI>();
            this.EXP_BankLoan = new HashSet<EXP_BankLoan>();
            this.EXP_BankVoucher = new HashSet<EXP_BankVoucher>();
        }
    
        public int BankID { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BankCategory { get; set; }
        public string BankType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string BankBINNo { get; set; }
        public string BankSwiftCode { get; set; }
    
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher { get; set; }
        public virtual ICollection<LCM_LimInfo> LCM_LimInfo { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Sys_Branch> Sys_Branch { get; set; }
        public virtual ICollection<EXP_BankDebitVoucher> EXP_BankDebitVoucher { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI { get; set; }
        public virtual ICollection<EXP_BankLoan> EXP_BankLoan { get; set; }
        public virtual ICollection<EXP_BankVoucher> EXP_BankVoucher { get; set; }
    }
}
