//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Grade
    {
        public Sys_Grade()
        {
            this.INV_WetBlueIssueItem = new HashSet<INV_WetBlueIssueItem>();
            this.INV_WetBlueSelectionStock = new HashSet<INV_WetBlueSelectionStock>();
            this.INV_WetBlueStockDaily = new HashSet<INV_WetBlueStockDaily>();
            this.INV_WetBlueStockItem = new HashSet<INV_WetBlueStockItem>();
            this.INV_WetBlueStockSupplier = new HashSet<INV_WetBlueStockSupplier>();
            this.PRD_CLProductionDrum = new HashSet<PRD_CLProductionDrum>();
            this.PRD_WBSelectionGrade = new HashSet<PRD_WBSelectionGrade>();
            this.PRD_WBSellectionIssueGrade = new HashSet<PRD_WBSellectionIssueGrade>();
            this.PRD_YearMonthCrustScheduleColor = new HashSet<PRD_YearMonthCrustScheduleColor>();
            this.PRD_YearMonthCrustScheduleDrum = new HashSet<PRD_YearMonthCrustScheduleDrum>();
            this.INV_CLTransferFrom = new HashSet<INV_CLTransferFrom>();
            this.INV_CLTransferTo = new HashSet<INV_CLTransferTo>();
            this.INV_CrustBuyerStock = new HashSet<INV_CrustBuyerStock>();
            this.INV_CrustLeatherIssueColor = new HashSet<INV_CrustLeatherIssueColor>();
            this.INV_CrustQCStock = new HashSet<INV_CrustQCStock>();
            this.INV_CrustStockDaily = new HashSet<INV_CrustStockDaily>();
            this.INV_CrustStockItem = new HashSet<INV_CrustStockItem>();
            this.PRD_CrustLeatherProductionStock = new HashSet<PRD_CrustLeatherProductionStock>();
            this.INV_CrustLeatherReceiveColor = new HashSet<INV_CrustLeatherReceiveColor>();
            this.INV_FinishBuyerStock = new HashSet<INV_FinishBuyerStock>();
            this.INV_FinishLeatherIssueColor = new HashSet<INV_FinishLeatherIssueColor>();
            this.INV_FinishLeatherReceiveColor = new HashSet<INV_FinishLeatherReceiveColor>();
            this.INV_FinishStockDaily = new HashSet<INV_FinishStockDaily>();
            this.INV_FinishStockItem = new HashSet<INV_FinishStockItem>();
            this.INV_FNTransferFrom = new HashSet<INV_FNTransferFrom>();
            this.INV_FNTransferTo = new HashSet<INV_FNTransferTo>();
            this.PRD_FinishLeatherProductionStock = new HashSet<PRD_FinishLeatherProductionStock>();
            this.PRD_FinishLeatherQCSelection = new HashSet<PRD_FinishLeatherQCSelection>();
            this.PRD_FNProductionDrum = new HashSet<PRD_FNProductionDrum>();
            this.PRD_YearMonthFinishScheduleColor = new HashSet<PRD_YearMonthFinishScheduleColor>();
            this.PRD_YearMonthFinishScheduleDrum = new HashSet<PRD_YearMonthFinishScheduleDrum>();
            this.INV_FinishBuyerQCStock = new HashSet<INV_FinishBuyerQCStock>();
            this.INV_FinishOwnQCStock = new HashSet<INV_FinishOwnQCStock>();
            this.EXP_PLPIItemColorBale = new HashSet<EXP_PLPIItemColorBale>();
            this.PRD_CrustLeatherQCSelection = new HashSet<PRD_CrustLeatherQCSelection>();
            this.INV_FinishPackingStock = new HashSet<INV_FinishPackingStock>();
        }
    
        public short GradeID { get; set; }
        public string GradeName { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<INV_WetBlueIssueItem> INV_WetBlueIssueItem { get; set; }
        public virtual ICollection<INV_WetBlueSelectionStock> INV_WetBlueSelectionStock { get; set; }
        public virtual ICollection<INV_WetBlueStockDaily> INV_WetBlueStockDaily { get; set; }
        public virtual ICollection<INV_WetBlueStockItem> INV_WetBlueStockItem { get; set; }
        public virtual ICollection<INV_WetBlueStockSupplier> INV_WetBlueStockSupplier { get; set; }
        public virtual ICollection<PRD_CLProductionDrum> PRD_CLProductionDrum { get; set; }
        public virtual ICollection<PRD_WBSelectionGrade> PRD_WBSelectionGrade { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueGrade> PRD_WBSellectionIssueGrade { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleColor> PRD_YearMonthCrustScheduleColor { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleDrum> PRD_YearMonthCrustScheduleDrum { get; set; }
        public virtual ICollection<INV_CLTransferFrom> INV_CLTransferFrom { get; set; }
        public virtual ICollection<INV_CLTransferTo> INV_CLTransferTo { get; set; }
        public virtual ICollection<INV_CrustBuyerStock> INV_CrustBuyerStock { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueColor> INV_CrustLeatherIssueColor { get; set; }
        public virtual ICollection<INV_CrustQCStock> INV_CrustQCStock { get; set; }
        public virtual ICollection<INV_CrustStockDaily> INV_CrustStockDaily { get; set; }
        public virtual ICollection<INV_CrustStockItem> INV_CrustStockItem { get; set; }
        public virtual ICollection<PRD_CrustLeatherProductionStock> PRD_CrustLeatherProductionStock { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveColor> INV_CrustLeatherReceiveColor { get; set; }
        public virtual ICollection<INV_FinishBuyerStock> INV_FinishBuyerStock { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueColor> INV_FinishLeatherIssueColor { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveColor> INV_FinishLeatherReceiveColor { get; set; }
        public virtual ICollection<INV_FinishStockDaily> INV_FinishStockDaily { get; set; }
        public virtual ICollection<INV_FinishStockItem> INV_FinishStockItem { get; set; }
        public virtual ICollection<INV_FNTransferFrom> INV_FNTransferFrom { get; set; }
        public virtual ICollection<INV_FNTransferTo> INV_FNTransferTo { get; set; }
        public virtual ICollection<PRD_FinishLeatherProductionStock> PRD_FinishLeatherProductionStock { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCSelection> PRD_FinishLeatherQCSelection { get; set; }
        public virtual ICollection<PRD_FNProductionDrum> PRD_FNProductionDrum { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleColor> PRD_YearMonthFinishScheduleColor { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleDrum> PRD_YearMonthFinishScheduleDrum { get; set; }
        public virtual ICollection<INV_FinishBuyerQCStock> INV_FinishBuyerQCStock { get; set; }
        public virtual ICollection<INV_FinishOwnQCStock> INV_FinishOwnQCStock { get; set; }
        public virtual ICollection<EXP_PLPIItemColorBale> EXP_PLPIItemColorBale { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCSelection> PRD_CrustLeatherQCSelection { get; set; }
        public virtual ICollection<INV_FinishPackingStock> INV_FinishPackingStock { get; set; }
    }
}
