//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Article
    {
        public Sys_Article()
        {
            this.PRD_Recipe = new HashSet<PRD_Recipe>();
            this.PRD_WBProduction = new HashSet<PRD_WBProduction>();
            this.PRD_WBProductionPurchase = new HashSet<PRD_WBProductionPurchase>();
            this.INV_CLTransferFrom = new HashSet<INV_CLTransferFrom>();
            this.INV_CLTransferTo = new HashSet<INV_CLTransferTo>();
            this.INV_CrustBuyerStock = new HashSet<INV_CrustBuyerStock>();
            this.INV_CrustQCStock = new HashSet<INV_CrustQCStock>();
            this.INV_CrustStockDaily = new HashSet<INV_CrustStockDaily>();
            this.INV_CrustStockItem = new HashSet<INV_CrustStockItem>();
            this.PRD_CrustLeatherProductionStock = new HashSet<PRD_CrustLeatherProductionStock>();
            this.INV_CrustLeatherReceiveItem = new HashSet<INV_CrustLeatherReceiveItem>();
            this.INV_FinishBuyerStock = new HashSet<INV_FinishBuyerStock>();
            this.INV_FinishLeatherIssueItem = new HashSet<INV_FinishLeatherIssueItem>();
            this.INV_FinishLeatherReceiveItem = new HashSet<INV_FinishLeatherReceiveItem>();
            this.INV_FinishStockDaily = new HashSet<INV_FinishStockDaily>();
            this.INV_FinishStockItem = new HashSet<INV_FinishStockItem>();
            this.INV_FNTransferFrom = new HashSet<INV_FNTransferFrom>();
            this.INV_FNTransferTo = new HashSet<INV_FNTransferTo>();
            this.PRD_FinishLeatherProductionStock = new HashSet<PRD_FinishLeatherProductionStock>();
            this.PRD_FinishLeatherQCItem = new HashSet<PRD_FinishLeatherQCItem>();
            this.INV_FinishBuyerQCStock = new HashSet<INV_FinishBuyerQCStock>();
            this.INV_FinishOwnQCStock = new HashSet<INV_FinishOwnQCStock>();
            this.PRD_CrustLeatherQCItem = new HashSet<PRD_CrustLeatherQCItem>();
            this.INV_CrustLeatherIssueItem = new HashSet<INV_CrustLeatherIssueItem>();
            this.EXP_CIPIItem = new HashSet<EXP_CIPIItem>();
            this.EXP_PLPIItemColor = new HashSet<EXP_PLPIItemColor>();
            this.INV_WetBlueIssueRef = new HashSet<INV_WetBlueIssueRef>();
            this.PRD_CLProductionItem = new HashSet<PRD_CLProductionItem>();
            this.PRD_FNProductionItem = new HashSet<PRD_FNProductionItem>();
            this.PRD_YearMonthCrustReqItem = new HashSet<PRD_YearMonthCrustReqItem>();
            this.PRD_YearMonthFinishReqItem = new HashSet<PRD_YearMonthFinishReqItem>();
            this.Sys_ArticleChallan = new HashSet<Sys_ArticleChallan>();
            this.INV_FinishPackingStock = new HashSet<INV_FinishPackingStock>();
            this.SLS_BuyerOrderDelivery = new HashSet<SLS_BuyerOrderDelivery>();
            this.SLS_BuyerOrderPrice = new HashSet<SLS_BuyerOrderPrice>();
            this.EXP_PIItem = new HashSet<EXP_PIItem>();
            this.SLS_BuyerOrderItem = new HashSet<SLS_BuyerOrderItem>();
        }
    
        public int ArticleID { get; set; }
        public string ArticleNo { get; set; }
        public string ArticleName { get; set; }
        public Nullable<int> ArticleColor { get; set; }
        public string ArticleChallanNo { get; set; }
        public string ArticleCategory { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<PRD_Recipe> PRD_Recipe { get; set; }
        public virtual ICollection<PRD_WBProduction> PRD_WBProduction { get; set; }
        public virtual ICollection<PRD_WBProductionPurchase> PRD_WBProductionPurchase { get; set; }
        public virtual Sys_Color Sys_Color { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<INV_CLTransferFrom> INV_CLTransferFrom { get; set; }
        public virtual ICollection<INV_CLTransferTo> INV_CLTransferTo { get; set; }
        public virtual ICollection<INV_CrustBuyerStock> INV_CrustBuyerStock { get; set; }
        public virtual ICollection<INV_CrustQCStock> INV_CrustQCStock { get; set; }
        public virtual ICollection<INV_CrustStockDaily> INV_CrustStockDaily { get; set; }
        public virtual ICollection<INV_CrustStockItem> INV_CrustStockItem { get; set; }
        public virtual ICollection<PRD_CrustLeatherProductionStock> PRD_CrustLeatherProductionStock { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveItem> INV_CrustLeatherReceiveItem { get; set; }
        public virtual ICollection<INV_FinishBuyerStock> INV_FinishBuyerStock { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueItem> INV_FinishLeatherIssueItem { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveItem> INV_FinishLeatherReceiveItem { get; set; }
        public virtual ICollection<INV_FinishStockDaily> INV_FinishStockDaily { get; set; }
        public virtual ICollection<INV_FinishStockItem> INV_FinishStockItem { get; set; }
        public virtual ICollection<INV_FNTransferFrom> INV_FNTransferFrom { get; set; }
        public virtual ICollection<INV_FNTransferTo> INV_FNTransferTo { get; set; }
        public virtual ICollection<PRD_FinishLeatherProductionStock> PRD_FinishLeatherProductionStock { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCItem> PRD_FinishLeatherQCItem { get; set; }
        public virtual ICollection<INV_FinishBuyerQCStock> INV_FinishBuyerQCStock { get; set; }
        public virtual ICollection<INV_FinishOwnQCStock> INV_FinishOwnQCStock { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCItem> PRD_CrustLeatherQCItem { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueItem> INV_CrustLeatherIssueItem { get; set; }
        public virtual ICollection<EXP_CIPIItem> EXP_CIPIItem { get; set; }
        public virtual ICollection<EXP_PLPIItemColor> EXP_PLPIItemColor { get; set; }
        public virtual ICollection<INV_WetBlueIssueRef> INV_WetBlueIssueRef { get; set; }
        public virtual ICollection<PRD_CLProductionItem> PRD_CLProductionItem { get; set; }
        public virtual ICollection<PRD_FNProductionItem> PRD_FNProductionItem { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItem> PRD_YearMonthCrustReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItem> PRD_YearMonthFinishReqItem { get; set; }
        public virtual ICollection<Sys_ArticleChallan> Sys_ArticleChallan { get; set; }
        public virtual ICollection<INV_FinishPackingStock> INV_FinishPackingStock { get; set; }
        public virtual ICollection<SLS_BuyerOrderDelivery> SLS_BuyerOrderDelivery { get; set; }
        public virtual ICollection<SLS_BuyerOrderPrice> SLS_BuyerOrderPrice { get; set; }
        public virtual ICollection<EXP_PIItem> EXP_PIItem { get; set; }
        public virtual ICollection<SLS_BuyerOrderItem> SLS_BuyerOrderItem { get; set; }
    }
}
