//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CompanyInfo
    {
        public Sys_CompanyInfo()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyTitle { get; set; }
        public string CompanySlogan { get; set; }
        public string CompanyAddress { get; set; }
        public string OverView { get; set; }
        public Nullable<int> BusinessType { get; set; }
        public Nullable<long> NoOfEmployee { get; set; }
        public string YearEstablish { get; set; }
        public string Keywords { get; set; }
        public string CompanyCity { get; set; }
        public string CompanyState { get; set; }
        public string CompanyPostalCode { get; set; }
        public Nullable<int> CompanyCountry { get; set; }
        public string CompanyPhone { get; set; }
        public string CompanyFax { get; set; }
        public string CompanyWebSite { get; set; }
        public string CompanyEmail { get; set; }
        public string BillingAddress { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public Nullable<int> BillingCountry { get; set; }
        public string BillingPhone { get; set; }
        public string ContactPersonTitle { get; set; }
        public string ContactPersonFirstName { get; set; }
        public string ContactPersonMiddleName { get; set; }
        public string ContactPersonLastName { get; set; }
        public Nullable<int> ContactPersonDesignation { get; set; }
        public Nullable<int> RegistrationType { get; set; }
        public Nullable<long> NoOfUsers { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ValidUpto { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CompanyCategoryID { get; set; }
        public Nullable<int> SMSBalance { get; set; }
        public Nullable<int> DiskSpace { get; set; }
        public string BusinessEmail { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
