//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_PreDefineValue
    {
        public int PreDefineValueID { get; set; }
        public Nullable<int> PreDefineValueForID { get; set; }
        public string PreDefineValueTitle { get; set; }
        public string PreDefineValueContent { get; set; }
        public string PreDefineValueGroup { get; set; }
        public string PreDefineValueIncreaseBy { get; set; }
        public string MaxValue { get; set; }
        public string InternalMailAddress { get; set; }
        public string InternalMailAutoSend { get; set; }
        public string ExternalMailAddress { get; set; }
        public string ExternalMailAutoSend { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual User User { get; set; }
        public virtual Sys_PreDefineValueFor Sys_PreDefineValueFor { get; set; }
        public virtual User User1 { get; set; }
    }
}
