//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ArticleChallanDetail
    {
        public long ArticleChallanDtlID { get; set; }
        public Nullable<long> ArticleChallanID { get; set; }
        public string SizeRange { get; set; }
        public Nullable<byte> SizeRangeUnit { get; set; }
        public string PcsSideDescription { get; set; }
        public string GradeRange { get; set; }
        public string ThicknessRange { get; set; }
        public Nullable<byte> ThicknessUnit { get; set; }
        public string ThicknessAt { get; set; }
        public string RequiredPercentage { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> SetOn { get; set; }
        public Nullable<int> SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual Sys_ArticleChallan Sys_ArticleChallan { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Sys_Unit Sys_Unit { get; set; }
        public virtual Sys_Unit Sys_Unit1 { get; set; }
    }
}
