//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_SupplierAddress
    {
        public Sys_SupplierAddress()
        {
            this.LCM_LCOpening = new HashSet<LCM_LCOpening>();
            this.Prq_BillPayment = new HashSet<Prq_BillPayment>();
            this.PRQ_ChemFrgnPurcRecv = new HashSet<PRQ_ChemFrgnPurcRecv>();
            this.PRQ_ChemicalPI = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemLocalPurcBill = new HashSet<PRQ_ChemLocalPurcBill>();
            this.PRQ_ChemLocalPurcBillPayment = new HashSet<PRQ_ChemLocalPurcBillPayment>();
            this.PRQ_ChemLocalPurcRecv = new HashSet<PRQ_ChemLocalPurcRecv>();
            this.Prq_PreGradeSelection = new HashSet<Prq_PreGradeSelection>();
            this.Prq_Purchase = new HashSet<Prq_Purchase>();
            this.Prq_SupplierBill = new HashSet<Prq_SupplierBill>();
            this.EXP_LeatherPI = new HashSet<EXP_LeatherPI>();
            this.EXP_LCOpening = new HashSet<EXP_LCOpening>();
        }
    
        public int SupplierAddressID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string FaxNo { get; set; }
        public string PhoneNo { get; set; }
        public string SkypeID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening { get; set; }
        public virtual ICollection<Prq_BillPayment> Prq_BillPayment { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecv> PRQ_ChemFrgnPurcRecv { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBill> PRQ_ChemLocalPurcBill { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillPayment> PRQ_ChemLocalPurcBillPayment { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecv> PRQ_ChemLocalPurcRecv { get; set; }
        public virtual ICollection<Prq_PreGradeSelection> Prq_PreGradeSelection { get; set; }
        public virtual ICollection<Prq_Purchase> Prq_Purchase { get; set; }
        public virtual ICollection<Prq_SupplierBill> Prq_SupplierBill { get; set; }
        public virtual Sys_Supplier Sys_Supplier { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening { get; set; }
    }
}
