//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Size
    {
        public Sys_Size()
        {
            this.INV_ChemStockDaily = new HashSet<INV_ChemStockDaily>();
            this.INV_ChemStockItem = new HashSet<INV_ChemStockItem>();
            this.INV_ChemStockSupplier = new HashSet<INV_ChemStockSupplier>();
            this.INV_StoreTransItem = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransItem1 = new HashSet<INV_StoreTransItem>();
            this.INV_TransRequestItem = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestItem1 = new HashSet<INV_TransRequestItem>();
            this.LCM_CommercialInvoiceItem = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_PackingListItem = new HashSet<LCM_PackingListItem>();
            this.PRD_ChemProdReqItem = new HashSet<PRD_ChemProdReqItem>();
            this.PRD_CLProductionChemical = new HashSet<PRD_CLProductionChemical>();
            this.PRD_WBProductionChemical = new HashSet<PRD_WBProductionChemical>();
            this.PRQ_ChemFrgnPurcOrdrItem = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcRecvItem = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemicalPIItem = new HashSet<PRQ_ChemicalPIItem>();
            this.PRQ_ChemLocalPurcBillItem = new HashSet<PRQ_ChemLocalPurcBillItem>();
            this.PRQ_ChemLocalPurcRecvItem = new HashSet<PRQ_ChemLocalPurcRecvItem>();
            this.PRQ_ChemPurcReqItem = new HashSet<PRQ_ChemPurcReqItem>();
            this.Prq_PurchaseChallanItem = new HashSet<Prq_PurchaseChallanItem>();
            this.Prq_PurchaseYearPeriodItem = new HashSet<Prq_PurchaseYearPeriodItem>();
            this.Prq_SupplierBillItem = new HashSet<Prq_SupplierBillItem>();
            this.PRD_FNProductionChemical = new HashSet<PRD_FNProductionChemical>();
            this.INV_WetBlueIssueItem = new HashSet<INV_WetBlueIssueItem>();
            this.INV_WetBlueSelectionStock = new HashSet<INV_WetBlueSelectionStock>();
            this.INV_WetBlueStockDaily = new HashSet<INV_WetBlueStockDaily>();
            this.INV_WetBlueStockItem = new HashSet<INV_WetBlueStockItem>();
            this.INV_WetBlueStockSupplier = new HashSet<INV_WetBlueStockSupplier>();
            this.PRD_WBSelectionGrade = new HashSet<PRD_WBSelectionGrade>();
            this.PRD_WBSellectionIssueGrade = new HashSet<PRD_WBSellectionIssueGrade>();
        }
    
        public byte SizeID { get; set; }
        public string SizeName { get; set; }
        public string SizeCategory { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<INV_ChemStockDaily> INV_ChemStockDaily { get; set; }
        public virtual ICollection<INV_ChemStockItem> INV_ChemStockItem { get; set; }
        public virtual ICollection<INV_ChemStockSupplier> INV_ChemStockSupplier { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem1 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem1 { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem { get; set; }
        public virtual ICollection<LCM_PackingListItem> LCM_PackingListItem { get; set; }
        public virtual ICollection<PRD_ChemProdReqItem> PRD_ChemProdReqItem { get; set; }
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemicalPIItem> PRQ_ChemicalPIItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillItem> PRQ_ChemLocalPurcBillItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem { get; set; }
        public virtual ICollection<Prq_PurchaseChallanItem> Prq_PurchaseChallanItem { get; set; }
        public virtual ICollection<Prq_PurchaseYearPeriodItem> Prq_PurchaseYearPeriodItem { get; set; }
        public virtual ICollection<Prq_SupplierBillItem> Prq_SupplierBillItem { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical { get; set; }
        public virtual ICollection<INV_WetBlueIssueItem> INV_WetBlueIssueItem { get; set; }
        public virtual ICollection<INV_WetBlueSelectionStock> INV_WetBlueSelectionStock { get; set; }
        public virtual ICollection<INV_WetBlueStockDaily> INV_WetBlueStockDaily { get; set; }
        public virtual ICollection<INV_WetBlueStockItem> INV_WetBlueStockItem { get; set; }
        public virtual ICollection<INV_WetBlueStockSupplier> INV_WetBlueStockSupplier { get; set; }
        public virtual ICollection<PRD_WBSelectionGrade> PRD_WBSelectionGrade { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueGrade> PRD_WBSellectionIssueGrade { get; set; }
    }
}
