//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.INV_ChemStockDaily = new HashSet<INV_ChemStockDaily>();
            this.INV_ChemStockDaily1 = new HashSet<INV_ChemStockDaily>();
            this.INV_ChemStockItem = new HashSet<INV_ChemStockItem>();
            this.INV_ChemStockItem1 = new HashSet<INV_ChemStockItem>();
            this.INV_ChemStockSupplier = new HashSet<INV_ChemStockSupplier>();
            this.INV_ChemStockSupplier1 = new HashSet<INV_ChemStockSupplier>();
            this.INV_CLTransfer = new HashSet<INV_CLTransfer>();
            this.INV_CLTransfer1 = new HashSet<INV_CLTransfer>();
            this.INV_CLTransfer2 = new HashSet<INV_CLTransfer>();
            this.INV_CLTransfer3 = new HashSet<INV_CLTransfer>();
            this.INV_CLTransfer4 = new HashSet<INV_CLTransfer>();
            this.INV_CrustLeatherIssue = new HashSet<INV_CrustLeatherIssue>();
            this.INV_CrustLeatherIssue1 = new HashSet<INV_CrustLeatherIssue>();
            this.INV_CrustLeatherIssue2 = new HashSet<INV_CrustLeatherIssue>();
            this.INV_CrustLeatherIssue3 = new HashSet<INV_CrustLeatherIssue>();
            this.INV_StoreTrans = new HashSet<INV_StoreTrans>();
            this.INV_StoreTrans1 = new HashSet<INV_StoreTrans>();
            this.INV_StoreTrans2 = new HashSet<INV_StoreTrans>();
            this.INV_StoreTransChallan = new HashSet<INV_StoreTransChallan>();
            this.INV_StoreTransChallan1 = new HashSet<INV_StoreTransChallan>();
            this.INV_StoreTransItem = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransItem1 = new HashSet<INV_StoreTransItem>();
            this.INV_StoreTransRequest = new HashSet<INV_StoreTransRequest>();
            this.INV_StoreTransRequest1 = new HashSet<INV_StoreTransRequest>();
            this.INV_TransRequest = new HashSet<INV_TransRequest>();
            this.INV_TransRequest1 = new HashSet<INV_TransRequest>();
            this.INV_TransRequest2 = new HashSet<INV_TransRequest>();
            this.INV_TransRequest3 = new HashSet<INV_TransRequest>();
            this.INV_TransRequest4 = new HashSet<INV_TransRequest>();
            this.INV_TransRequestItem = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestItem1 = new HashSet<INV_TransRequestItem>();
            this.INV_TransRequestRef = new HashSet<INV_TransRequestRef>();
            this.INV_TransRequestRef1 = new HashSet<INV_TransRequestRef>();
            this.INV_TransRequestRef2 = new HashSet<INV_TransRequestRef>();
            this.INV_WetBlueIssue = new HashSet<INV_WetBlueIssue>();
            this.INV_WetBlueIssue1 = new HashSet<INV_WetBlueIssue>();
            this.INV_WetBlueIssue2 = new HashSet<INV_WetBlueIssue>();
            this.INV_WetBlueIssue3 = new HashSet<INV_WetBlueIssue>();
            this.INV_WetBlueIssue4 = new HashSet<INV_WetBlueIssue>();
            this.INV_WetBlueIssueItem = new HashSet<INV_WetBlueIssueItem>();
            this.INV_WetBlueIssueItem1 = new HashSet<INV_WetBlueIssueItem>();
            this.LCM_BankDebitVoucher = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_BankDebitVoucher1 = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_BankDebitVoucher2 = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_BankDebitVoucher3 = new HashSet<LCM_BankDebitVoucher>();
            this.LCM_BillofLading = new HashSet<LCM_BillofLading>();
            this.LCM_BillofLading1 = new HashSet<LCM_BillofLading>();
            this.LCM_BillofLading2 = new HashSet<LCM_BillofLading>();
            this.LCM_CnfBill = new HashSet<LCM_CnfBill>();
            this.LCM_CnfBill1 = new HashSet<LCM_CnfBill>();
            this.LCM_CommercialInvoice = new HashSet<LCM_CommercialInvoice>();
            this.LCM_CommercialInvoice1 = new HashSet<LCM_CommercialInvoice>();
            this.LCM_CommercialInvoiceItem = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_CommercialInvoiceItem1 = new HashSet<LCM_CommercialInvoiceItem>();
            this.LCM_Insurence = new HashSet<LCM_Insurence>();
            this.LCM_Insurence1 = new HashSet<LCM_Insurence>();
            this.LCM_Insurence2 = new HashSet<LCM_Insurence>();
            this.LCM_Insurence3 = new HashSet<LCM_Insurence>();
            this.LCM_LCOpening = new HashSet<LCM_LCOpening>();
            this.LCM_LCOpening1 = new HashSet<LCM_LCOpening>();
            this.LCM_LCOpening2 = new HashSet<LCM_LCOpening>();
            this.LCM_LCOpening3 = new HashSet<LCM_LCOpening>();
            this.LCM_LCRetirement = new HashSet<LCM_LCRetirement>();
            this.LCM_LCRetirement1 = new HashSet<LCM_LCRetirement>();
            this.LCM_LimInfo = new HashSet<LCM_LimInfo>();
            this.LCM_LimInfo1 = new HashSet<LCM_LimInfo>();
            this.LCM_PackingList = new HashSet<LCM_PackingList>();
            this.LCM_PackingList1 = new HashSet<LCM_PackingList>();
            this.LCM_PackingList2 = new HashSet<LCM_PackingList>();
            this.LCM_PackingListItem = new HashSet<LCM_PackingListItem>();
            this.LCM_PackingListItem1 = new HashSet<LCM_PackingListItem>();
            this.LCM_PackingListPacks = new HashSet<LCM_PackingListPacks>();
            this.LCM_PackingListPacks1 = new HashSet<LCM_PackingListPacks>();
            this.PRD_ChemProdReq = new HashSet<PRD_ChemProdReq>();
            this.PRD_ChemProdReq1 = new HashSet<PRD_ChemProdReq>();
            this.PRD_ChemProdReq2 = new HashSet<PRD_ChemProdReq>();
            this.PRD_ChemProdReq3 = new HashSet<PRD_ChemProdReq>();
            this.PRD_ChemProdReq4 = new HashSet<PRD_ChemProdReq>();
            this.PRD_ChemProdReq5 = new HashSet<PRD_ChemProdReq>();
            this.PRD_ChemProdReqItem = new HashSet<PRD_ChemProdReqItem>();
            this.PRD_ChemProdReqItem1 = new HashSet<PRD_ChemProdReqItem>();
            this.PRD_CLProduction = new HashSet<PRD_CLProduction>();
            this.PRD_CLProduction1 = new HashSet<PRD_CLProduction>();
            this.PRD_CLProduction2 = new HashSet<PRD_CLProduction>();
            this.PRD_CLProduction3 = new HashSet<PRD_CLProduction>();
            this.PRD_CLProduction4 = new HashSet<PRD_CLProduction>();
            this.PRD_CLProductionChemical = new HashSet<PRD_CLProductionChemical>();
            this.PRD_CLProductionChemical1 = new HashSet<PRD_CLProductionChemical>();
            this.PRD_CLProductionColor = new HashSet<PRD_CLProductionColor>();
            this.PRD_CLProductionColor1 = new HashSet<PRD_CLProductionColor>();
            this.PRD_CLProductionDrum = new HashSet<PRD_CLProductionDrum>();
            this.PRD_CLProductionDrum1 = new HashSet<PRD_CLProductionDrum>();
            this.PRD_CrustLeatherQC = new HashSet<PRD_CrustLeatherQC>();
            this.PRD_CrustLeatherQC1 = new HashSet<PRD_CrustLeatherQC>();
            this.PRD_CrustLeatherQC2 = new HashSet<PRD_CrustLeatherQC>();
            this.PRD_CrustLeatherQC3 = new HashSet<PRD_CrustLeatherQC>();
            this.PRD_CrustLeatherQC4 = new HashSet<PRD_CrustLeatherQC>();
            this.PRD_Recipe = new HashSet<PRD_Recipe>();
            this.PRD_Recipe1 = new HashSet<PRD_Recipe>();
            this.PRD_RecipeItem = new HashSet<PRD_RecipeItem>();
            this.PRD_RecipeItem1 = new HashSet<PRD_RecipeItem>();
            this.PRD_WBProduction = new HashSet<PRD_WBProduction>();
            this.PRD_WBProduction1 = new HashSet<PRD_WBProduction>();
            this.PRD_WBProduction2 = new HashSet<PRD_WBProduction>();
            this.PRD_WBProduction3 = new HashSet<PRD_WBProduction>();
            this.PRD_WBProduction4 = new HashSet<PRD_WBProduction>();
            this.PRD_WBProductionChemical = new HashSet<PRD_WBProductionChemical>();
            this.PRD_WBProductionChemical1 = new HashSet<PRD_WBProductionChemical>();
            this.PRD_WBProductionPurchase = new HashSet<PRD_WBProductionPurchase>();
            this.PRD_WBProductionPurchase1 = new HashSet<PRD_WBProductionPurchase>();
            this.PRD_WBSelection = new HashSet<PRD_WBSelection>();
            this.PRD_WBSelection1 = new HashSet<PRD_WBSelection>();
            this.PRD_WBSelection2 = new HashSet<PRD_WBSelection>();
            this.PRD_WBSelection3 = new HashSet<PRD_WBSelection>();
            this.PRD_WBSelection4 = new HashSet<PRD_WBSelection>();
            this.PRD_WBSelectionGrade = new HashSet<PRD_WBSelectionGrade>();
            this.PRD_WBSelectionGrade1 = new HashSet<PRD_WBSelectionGrade>();
            this.PRD_WBSellectionIssue = new HashSet<PRD_WBSellectionIssue>();
            this.PRD_WBSellectionIssue1 = new HashSet<PRD_WBSellectionIssue>();
            this.PRD_WBSellectionIssue2 = new HashSet<PRD_WBSellectionIssue>();
            this.PRD_WBSellectionIssue3 = new HashSet<PRD_WBSellectionIssue>();
            this.PRD_WBSellectionIssueGrade = new HashSet<PRD_WBSellectionIssueGrade>();
            this.PRD_WBSellectionIssueGrade1 = new HashSet<PRD_WBSellectionIssueGrade>();
            this.PRD_WBSellectionIssueItem = new HashSet<PRD_WBSellectionIssueItem>();
            this.PRD_WBSellectionIssueItem1 = new HashSet<PRD_WBSellectionIssueItem>();
            this.PRD_YearMonth = new HashSet<PRD_YearMonth>();
            this.PRD_YearMonth1 = new HashSet<PRD_YearMonth>();
            this.PRD_YearMonthCrustReqDate = new HashSet<PRD_YearMonthCrustReqDate>();
            this.PRD_YearMonthCrustReqDate1 = new HashSet<PRD_YearMonthCrustReqDate>();
            this.PRD_YearMonthCrustReqItemColor = new HashSet<PRD_YearMonthCrustReqItemColor>();
            this.PRD_YearMonthCrustReqItemColor1 = new HashSet<PRD_YearMonthCrustReqItemColor>();
            this.PRD_YearMonthCrustScheduleColor = new HashSet<PRD_YearMonthCrustScheduleColor>();
            this.PRD_YearMonthCrustScheduleColor1 = new HashSet<PRD_YearMonthCrustScheduleColor>();
            this.PRD_YearMonthCrustScheduleDrum = new HashSet<PRD_YearMonthCrustScheduleDrum>();
            this.PRD_YearMonthCrustScheduleDrum1 = new HashSet<PRD_YearMonthCrustScheduleDrum>();
            this.PRD_YearMonthSchedule = new HashSet<PRD_YearMonthSchedule>();
            this.PRD_YearMonthSchedule1 = new HashSet<PRD_YearMonthSchedule>();
            this.PRD_YearMonthSchedule2 = new HashSet<PRD_YearMonthSchedule>();
            this.PRD_YearMonthSchedule3 = new HashSet<PRD_YearMonthSchedule>();
            this.PRD_YearMonthScheduleDate = new HashSet<PRD_YearMonthScheduleDate>();
            this.PRD_YearMonthScheduleDate1 = new HashSet<PRD_YearMonthScheduleDate>();
            this.PRD_YearMonthSchedulePurchase = new HashSet<PRD_YearMonthSchedulePurchase>();
            this.PRD_YearMonthSchedulePurchase1 = new HashSet<PRD_YearMonthSchedulePurchase>();
            this.PRQ_ChemBillPymtReference = new HashSet<PRQ_ChemBillPymtReference>();
            this.PRQ_ChemBillPymtReference1 = new HashSet<PRQ_ChemBillPymtReference>();
            this.PRQ_ChemBillRealization = new HashSet<PRQ_ChemBillRealization>();
            this.PRQ_ChemBillRealization1 = new HashSet<PRQ_ChemBillRealization>();
            this.PRQ_ChemBillRealization2 = new HashSet<PRQ_ChemBillRealization>();
            this.PRQ_ChemBillRealization3 = new HashSet<PRQ_ChemBillRealization>();
            this.PRQ_ChemFrgnPurcOrdr = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdr1 = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdr2 = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdr3 = new HashSet<PRQ_ChemFrgnPurcOrdr>();
            this.PRQ_ChemFrgnPurcOrdrItem = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcOrdrItem1 = new HashSet<PRQ_ChemFrgnPurcOrdrItem>();
            this.PRQ_ChemFrgnPurcOrdrRqsn = new HashSet<PRQ_ChemFrgnPurcOrdrRqsn>();
            this.PRQ_ChemFrgnPurcOrdrRqsn1 = new HashSet<PRQ_ChemFrgnPurcOrdrRqsn>();
            this.PRQ_ChemFrgnPurcRecv = new HashSet<PRQ_ChemFrgnPurcRecv>();
            this.PRQ_ChemFrgnPurcRecv1 = new HashSet<PRQ_ChemFrgnPurcRecv>();
            this.PRQ_ChemFrgnPurcRecv2 = new HashSet<PRQ_ChemFrgnPurcRecv>();
            this.PRQ_ChemFrgnPurcRecv3 = new HashSet<PRQ_ChemFrgnPurcRecv>();
            this.PRQ_ChemFrgnPurcRecvChallan = new HashSet<PRQ_ChemFrgnPurcRecvChallan>();
            this.PRQ_ChemFrgnPurcRecvChallan1 = new HashSet<PRQ_ChemFrgnPurcRecvChallan>();
            this.PRQ_ChemFrgnPurcRecvItem = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemFrgnPurcRecvItem1 = new HashSet<PRQ_ChemFrgnPurcRecvItem>();
            this.PRQ_ChemFrgnPurcRecvPL = new HashSet<PRQ_ChemFrgnPurcRecvPL>();
            this.PRQ_ChemFrgnPurcRecvPL1 = new HashSet<PRQ_ChemFrgnPurcRecvPL>();
            this.PRQ_ChemFrgnPurcRecvPL2 = new HashSet<PRQ_ChemFrgnPurcRecvPL>();
            this.PRQ_ChemicalPI = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPI1 = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPI2 = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPI3 = new HashSet<PRQ_ChemicalPI>();
            this.PRQ_ChemicalPIItem = new HashSet<PRQ_ChemicalPIItem>();
            this.PRQ_ChemicalPIItem1 = new HashSet<PRQ_ChemicalPIItem>();
            this.PRQ_ChemLocalPurcBill = new HashSet<PRQ_ChemLocalPurcBill>();
            this.PRQ_ChemLocalPurcBill1 = new HashSet<PRQ_ChemLocalPurcBill>();
            this.PRQ_ChemLocalPurcBill2 = new HashSet<PRQ_ChemLocalPurcBill>();
            this.PRQ_ChemLocalPurcBill3 = new HashSet<PRQ_ChemLocalPurcBill>();
            this.PRQ_ChemLocalPurcBillItem = new HashSet<PRQ_ChemLocalPurcBillItem>();
            this.PRQ_ChemLocalPurcBillItem1 = new HashSet<PRQ_ChemLocalPurcBillItem>();
            this.PRQ_ChemLocalPurcBillPayment = new HashSet<PRQ_ChemLocalPurcBillPayment>();
            this.PRQ_ChemLocalPurcBillPayment1 = new HashSet<PRQ_ChemLocalPurcBillPayment>();
            this.PRQ_ChemLocalPurcBillPayment2 = new HashSet<PRQ_ChemLocalPurcBillPayment>();
            this.PRQ_ChemLocalPurcBillPayment3 = new HashSet<PRQ_ChemLocalPurcBillPayment>();
            this.PRQ_ChemLocalPurcBillRef = new HashSet<PRQ_ChemLocalPurcBillRef>();
            this.PRQ_ChemLocalPurcBillRef1 = new HashSet<PRQ_ChemLocalPurcBillRef>();
            this.PRQ_ChemLocalPurcRecv = new HashSet<PRQ_ChemLocalPurcRecv>();
            this.PRQ_ChemLocalPurcRecv1 = new HashSet<PRQ_ChemLocalPurcRecv>();
            this.PRQ_ChemLocalPurcRecv2 = new HashSet<PRQ_ChemLocalPurcRecv>();
            this.PRQ_ChemLocalPurcRecv3 = new HashSet<PRQ_ChemLocalPurcRecv>();
            this.PRQ_ChemLocalPurcRecvChallan = new HashSet<PRQ_ChemLocalPurcRecvChallan>();
            this.PRQ_ChemLocalPurcRecvChallan1 = new HashSet<PRQ_ChemLocalPurcRecvChallan>();
            this.PRQ_ChemLocalPurcRecvItem = new HashSet<PRQ_ChemLocalPurcRecvItem>();
            this.PRQ_ChemLocalPurcRecvItem1 = new HashSet<PRQ_ChemLocalPurcRecvItem>();
            this.PRQ_ChemLocalPurcRecvPO = new HashSet<PRQ_ChemLocalPurcRecvPO>();
            this.PRQ_ChemLocalPurcRecvPO1 = new HashSet<PRQ_ChemLocalPurcRecvPO>();
            this.PRQ_ChemPurcReq = new HashSet<PRQ_ChemPurcReq>();
            this.PRQ_ChemPurcReq1 = new HashSet<PRQ_ChemPurcReq>();
            this.PRQ_ChemPurcReq2 = new HashSet<PRQ_ChemPurcReq>();
            this.PRQ_ChemPurcReq3 = new HashSet<PRQ_ChemPurcReq>();
            this.PRQ_ChemPurcReq4 = new HashSet<PRQ_ChemPurcReq>();
            this.PRQ_ChemPurcReq5 = new HashSet<PRQ_ChemPurcReq>();
            this.PRQ_ChemPurcReqItem = new HashSet<PRQ_ChemPurcReqItem>();
            this.PRQ_ChemPurcReqItem1 = new HashSet<PRQ_ChemPurcReqItem>();
            this.SLS_BuyerOrder = new HashSet<SLS_BuyerOrder>();
            this.SLS_BuyerOrder1 = new HashSet<SLS_BuyerOrder>();
            this.SLS_BuyerOrder2 = new HashSet<SLS_BuyerOrder>();
            this.SLS_BuyerOrder3 = new HashSet<SLS_BuyerOrder>();
            this.SLS_BuyerOrder4 = new HashSet<SLS_BuyerOrder>();
            this.Sys_Article = new HashSet<Sys_Article>();
            this.Sys_Article1 = new HashSet<Sys_Article>();
            this.Sys_Bank = new HashSet<Sys_Bank>();
            this.Sys_Bank1 = new HashSet<Sys_Bank>();
            this.Sys_Branch = new HashSet<Sys_Branch>();
            this.Sys_Branch1 = new HashSet<Sys_Branch>();
            this.Sys_Buyer = new HashSet<Sys_Buyer>();
            this.Sys_Buyer1 = new HashSet<Sys_Buyer>();
            this.Sys_BuyerAddress = new HashSet<Sys_BuyerAddress>();
            this.Sys_BuyerAddress1 = new HashSet<Sys_BuyerAddress>();
            this.Sys_BuyerAgent = new HashSet<Sys_BuyerAgent>();
            this.Sys_BuyerAgent1 = new HashSet<Sys_BuyerAgent>();
            this.Sys_ChemicalItem = new HashSet<Sys_ChemicalItem>();
            this.Sys_ChemicalItem1 = new HashSet<Sys_ChemicalItem>();
            this.Sys_Color = new HashSet<Sys_Color>();
            this.Sys_Color1 = new HashSet<Sys_Color>();
            this.Sys_Country = new HashSet<Sys_Country>();
            this.Sys_Country1 = new HashSet<Sys_Country>();
            this.Sys_Machine = new HashSet<Sys_Machine>();
            this.Sys_Machine1 = new HashSet<Sys_Machine>();
            this.Sys_Port = new HashSet<Sys_Port>();
            this.Sys_Port1 = new HashSet<Sys_Port>();
            this.Sys_PreDefineValue = new HashSet<Sys_PreDefineValue>();
            this.Sys_PreDefineValue1 = new HashSet<Sys_PreDefineValue>();
            this.Sys_PreDefineValueFor = new HashSet<Sys_PreDefineValueFor>();
            this.Sys_PreDefineValueFor1 = new HashSet<Sys_PreDefineValueFor>();
            this.Sys_ProductionProces = new HashSet<Sys_ProductionProces>();
            this.Sys_ProductionProces1 = new HashSet<Sys_ProductionProces>();
            this.AccessLogs = new HashSet<AccessLog>();
            this.AdditionalOperationPermissions = new HashSet<AdditionalOperationPermission>();
            this.AdditionalScreenPermissions = new HashSet<AdditionalScreenPermission>();
            this.UserInRoles = new HashSet<UserInRole>();
            this.INV_CLTransferFrom = new HashSet<INV_CLTransferFrom>();
            this.INV_CLTransferFrom1 = new HashSet<INV_CLTransferFrom>();
            this.INV_CLTransferTo = new HashSet<INV_CLTransferTo>();
            this.INV_CLTransferTo1 = new HashSet<INV_CLTransferTo>();
            this.INV_CrustLeatherIssueColor = new HashSet<INV_CrustLeatherIssueColor>();
            this.INV_CrustLeatherIssueColor1 = new HashSet<INV_CrustLeatherIssueColor>();
            this.PRD_WBSelectionItem = new HashSet<PRD_WBSelectionItem>();
            this.PRD_WBSelectionItem1 = new HashSet<PRD_WBSelectionItem>();
            this.PRD_CrustLeatherQCRef = new HashSet<PRD_CrustLeatherQCRef>();
            this.PRD_CrustLeatherQCRef1 = new HashSet<PRD_CrustLeatherQCRef>();
            this.INV_CrustLeatherReceive = new HashSet<INV_CrustLeatherReceive>();
            this.INV_CrustLeatherReceive1 = new HashSet<INV_CrustLeatherReceive>();
            this.INV_CrustLeatherReceive2 = new HashSet<INV_CrustLeatherReceive>();
            this.INV_CrustLeatherReceive3 = new HashSet<INV_CrustLeatherReceive>();
            this.INV_CrustLeatherReceiveColor = new HashSet<INV_CrustLeatherReceiveColor>();
            this.INV_CrustLeatherReceiveColor1 = new HashSet<INV_CrustLeatherReceiveColor>();
            this.INV_CrustLeatherReceiveItem = new HashSet<INV_CrustLeatherReceiveItem>();
            this.INV_CrustLeatherReceiveItem1 = new HashSet<INV_CrustLeatherReceiveItem>();
            this.INV_CrustLeatherReceiveRef = new HashSet<INV_CrustLeatherReceiveRef>();
            this.INV_CrustLeatherReceiveRef1 = new HashSet<INV_CrustLeatherReceiveRef>();
            this.INV_CrustLeatherReceiveRef2 = new HashSet<INV_CrustLeatherReceiveRef>();
            this.INV_CrustLeatherReceiveRef3 = new HashSet<INV_CrustLeatherReceiveRef>();
            this.INV_FinishLeatherIssue = new HashSet<INV_FinishLeatherIssue>();
            this.INV_FinishLeatherIssue1 = new HashSet<INV_FinishLeatherIssue>();
            this.INV_FinishLeatherIssue2 = new HashSet<INV_FinishLeatherIssue>();
            this.INV_FinishLeatherIssue3 = new HashSet<INV_FinishLeatherIssue>();
            this.INV_FinishLeatherIssueColor = new HashSet<INV_FinishLeatherIssueColor>();
            this.INV_FinishLeatherIssueColor1 = new HashSet<INV_FinishLeatherIssueColor>();
            this.INV_FinishLeatherIssueItem = new HashSet<INV_FinishLeatherIssueItem>();
            this.INV_FinishLeatherIssueItem1 = new HashSet<INV_FinishLeatherIssueItem>();
            this.INV_FinishLeatherReceive = new HashSet<INV_FinishLeatherReceive>();
            this.INV_FinishLeatherReceive1 = new HashSet<INV_FinishLeatherReceive>();
            this.INV_FinishLeatherReceive2 = new HashSet<INV_FinishLeatherReceive>();
            this.INV_FinishLeatherReceive3 = new HashSet<INV_FinishLeatherReceive>();
            this.INV_FinishLeatherReceiveColor = new HashSet<INV_FinishLeatherReceiveColor>();
            this.INV_FinishLeatherReceiveColor1 = new HashSet<INV_FinishLeatherReceiveColor>();
            this.INV_FinishLeatherReceiveItem = new HashSet<INV_FinishLeatherReceiveItem>();
            this.INV_FinishLeatherReceiveItem1 = new HashSet<INV_FinishLeatherReceiveItem>();
            this.INV_FinishLeatherReceiveRef = new HashSet<INV_FinishLeatherReceiveRef>();
            this.INV_FinishLeatherReceiveRef1 = new HashSet<INV_FinishLeatherReceiveRef>();
            this.INV_FinishLeatherReceiveRef2 = new HashSet<INV_FinishLeatherReceiveRef>();
            this.INV_FinishLeatherReceiveRef3 = new HashSet<INV_FinishLeatherReceiveRef>();
            this.INV_FNTransfer = new HashSet<INV_FNTransfer>();
            this.INV_FNTransfer1 = new HashSet<INV_FNTransfer>();
            this.INV_FNTransfer2 = new HashSet<INV_FNTransfer>();
            this.INV_FNTransfer3 = new HashSet<INV_FNTransfer>();
            this.INV_FNTransfer4 = new HashSet<INV_FNTransfer>();
            this.INV_FNTransferFrom = new HashSet<INV_FNTransferFrom>();
            this.INV_FNTransferFrom1 = new HashSet<INV_FNTransferFrom>();
            this.INV_FNTransferTo = new HashSet<INV_FNTransferTo>();
            this.INV_FNTransferTo1 = new HashSet<INV_FNTransferTo>();
            this.PRD_FinishLeatherQC = new HashSet<PRD_FinishLeatherQC>();
            this.PRD_FinishLeatherQC1 = new HashSet<PRD_FinishLeatherQC>();
            this.PRD_FinishLeatherQC2 = new HashSet<PRD_FinishLeatherQC>();
            this.PRD_FinishLeatherQC3 = new HashSet<PRD_FinishLeatherQC>();
            this.PRD_FinishLeatherQC4 = new HashSet<PRD_FinishLeatherQC>();
            this.PRD_FinishLeatherQCItem = new HashSet<PRD_FinishLeatherQCItem>();
            this.PRD_FinishLeatherQCItem1 = new HashSet<PRD_FinishLeatherQCItem>();
            this.PRD_FinishLeatherQCRef = new HashSet<PRD_FinishLeatherQCRef>();
            this.PRD_FinishLeatherQCRef1 = new HashSet<PRD_FinishLeatherQCRef>();
            this.PRD_FinishLeatherQCSelection = new HashSet<PRD_FinishLeatherQCSelection>();
            this.PRD_FinishLeatherQCSelection1 = new HashSet<PRD_FinishLeatherQCSelection>();
            this.PRD_FNProduction = new HashSet<PRD_FNProduction>();
            this.PRD_FNProduction1 = new HashSet<PRD_FNProduction>();
            this.PRD_FNProduction2 = new HashSet<PRD_FNProduction>();
            this.PRD_FNProduction3 = new HashSet<PRD_FNProduction>();
            this.PRD_FNProduction4 = new HashSet<PRD_FNProduction>();
            this.PRD_FNProductionChemical = new HashSet<PRD_FNProductionChemical>();
            this.PRD_FNProductionChemical1 = new HashSet<PRD_FNProductionChemical>();
            this.PRD_FNProductionColor = new HashSet<PRD_FNProductionColor>();
            this.PRD_FNProductionColor1 = new HashSet<PRD_FNProductionColor>();
            this.PRD_FNProductionDrum = new HashSet<PRD_FNProductionDrum>();
            this.PRD_FNProductionDrum1 = new HashSet<PRD_FNProductionDrum>();
            this.PRD_YearMonthFinishReqDate = new HashSet<PRD_YearMonthFinishReqDate>();
            this.PRD_YearMonthFinishReqDate1 = new HashSet<PRD_YearMonthFinishReqDate>();
            this.PRD_YearMonthFinishReqItemColor = new HashSet<PRD_YearMonthFinishReqItemColor>();
            this.PRD_YearMonthFinishReqItemColor1 = new HashSet<PRD_YearMonthFinishReqItemColor>();
            this.PRD_YearMonthFinishScheduleColor = new HashSet<PRD_YearMonthFinishScheduleColor>();
            this.PRD_YearMonthFinishScheduleColor1 = new HashSet<PRD_YearMonthFinishScheduleColor>();
            this.PRD_YearMonthFinishScheduleDrum = new HashSet<PRD_YearMonthFinishScheduleDrum>();
            this.PRD_YearMonthFinishScheduleDrum1 = new HashSet<PRD_YearMonthFinishScheduleDrum>();
            this.LCM_LCFile = new HashSet<LCM_LCFile>();
            this.LCM_LCFile1 = new HashSet<LCM_LCFile>();
            this.LCM_LCFile2 = new HashSet<LCM_LCFile>();
            this.LCM_LCFile3 = new HashSet<LCM_LCFile>();
            this.LCM_LCFileRecord = new HashSet<LCM_LCFileRecord>();
            this.LCM_LCFileRecord1 = new HashSet<LCM_LCFileRecord>();
            this.LCM_LCFileRecord2 = new HashSet<LCM_LCFileRecord>();
            this.LCM_LCFileRecord3 = new HashSet<LCM_LCFileRecord>();
            this.EXP_BillofLading = new HashSet<EXP_BillofLading>();
            this.EXP_BillofLading1 = new HashSet<EXP_BillofLading>();
            this.EXP_BillofLading2 = new HashSet<EXP_BillofLading>();
            this.EXP_CI = new HashSet<EXP_CI>();
            this.EXP_CI1 = new HashSet<EXP_CI>();
            this.EXP_CIPI = new HashSet<EXP_CIPI>();
            this.EXP_CIPI1 = new HashSet<EXP_CIPI>();
            this.EXP_CnFBill = new HashSet<EXP_CnFBill>();
            this.EXP_CnFBill1 = new HashSet<EXP_CnFBill>();
            this.EXP_LCOpening = new HashSet<EXP_LCOpening>();
            this.EXP_LCOpening1 = new HashSet<EXP_LCOpening>();
            this.EXP_LCOpening2 = new HashSet<EXP_LCOpening>();
            this.EXP_LCOpening3 = new HashSet<EXP_LCOpening>();
            this.EXP_LeatherPI = new HashSet<EXP_LeatherPI>();
            this.EXP_LeatherPI1 = new HashSet<EXP_LeatherPI>();
            this.EXP_LeatherPI2 = new HashSet<EXP_LeatherPI>();
            this.EXP_LeatherPI3 = new HashSet<EXP_LeatherPI>();
            this.EXP_PackingList = new HashSet<EXP_PackingList>();
            this.EXP_PackingList1 = new HashSet<EXP_PackingList>();
            this.EXP_PackingList2 = new HashSet<EXP_PackingList>();
            this.EXP_PLPI = new HashSet<EXP_PLPI>();
            this.EXP_PLPI1 = new HashSet<EXP_PLPI>();
            this.EXP_PLPIItemColorBale = new HashSet<EXP_PLPIItemColorBale>();
            this.EXP_PLPIItemColorBale1 = new HashSet<EXP_PLPIItemColorBale>();
            this.EXP_AgentCommissionBuyer = new HashSet<EXP_AgentCommissionBuyer>();
            this.EXP_AgentCommissionBuyer1 = new HashSet<EXP_AgentCommissionBuyer>();
            this.EXP_BankDebitVoucher = new HashSet<EXP_BankDebitVoucher>();
            this.EXP_BankDebitVoucher1 = new HashSet<EXP_BankDebitVoucher>();
            this.EXP_DeliveryChallan = new HashSet<EXP_DeliveryChallan>();
            this.EXP_DeliveryChallan1 = new HashSet<EXP_DeliveryChallan>();
            this.EXP_DeliveryChallan2 = new HashSet<EXP_DeliveryChallan>();
            this.EXP_DeliveryChallanCI = new HashSet<EXP_DeliveryChallanCI>();
            this.EXP_DeliveryChallanCI1 = new HashSet<EXP_DeliveryChallanCI>();
            this.EXP_ExportForm = new HashSet<EXP_ExportForm>();
            this.EXP_ExportForm1 = new HashSet<EXP_ExportForm>();
            this.EXP_LCRetirement = new HashSet<EXP_LCRetirement>();
            this.EXP_LCRetirement1 = new HashSet<EXP_LCRetirement>();
            this.EXP_TransportChallan = new HashSet<EXP_TransportChallan>();
            this.EXP_TransportChallan1 = new HashSet<EXP_TransportChallan>();
            this.EXP_TransportChallan2 = new HashSet<EXP_TransportChallan>();
            this.EXP_TransportChallanCI = new HashSet<EXP_TransportChallanCI>();
            this.EXP_TransportChallanCI1 = new HashSet<EXP_TransportChallanCI>();
            this.PRD_CrustLeatherQCItem = new HashSet<PRD_CrustLeatherQCItem>();
            this.PRD_CrustLeatherQCItem1 = new HashSet<PRD_CrustLeatherQCItem>();
            this.PRD_CrustLeatherQCSelection = new HashSet<PRD_CrustLeatherQCSelection>();
            this.PRD_CrustLeatherQCSelection1 = new HashSet<PRD_CrustLeatherQCSelection>();
            this.INV_CrustLeatherIssueItem = new HashSet<INV_CrustLeatherIssueItem>();
            this.INV_CrustLeatherIssueItem1 = new HashSet<INV_CrustLeatherIssueItem>();
            this.EXP_CIPIItem = new HashSet<EXP_CIPIItem>();
            this.EXP_CIPIItem1 = new HashSet<EXP_CIPIItem>();
            this.EXP_CIPIItemColor = new HashSet<EXP_CIPIItemColor>();
            this.EXP_CIPIItemColor1 = new HashSet<EXP_CIPIItemColor>();
            this.EXP_PLPIItemColor = new HashSet<EXP_PLPIItemColor>();
            this.EXP_PLPIItemColor1 = new HashSet<EXP_PLPIItemColor>();
            this.INV_WetBlueIssueRef = new HashSet<INV_WetBlueIssueRef>();
            this.INV_WetBlueIssueRef1 = new HashSet<INV_WetBlueIssueRef>();
            this.PRD_CLProductionItem = new HashSet<PRD_CLProductionItem>();
            this.PRD_CLProductionItem1 = new HashSet<PRD_CLProductionItem>();
            this.PRD_FNProductionItem = new HashSet<PRD_FNProductionItem>();
            this.PRD_FNProductionItem1 = new HashSet<PRD_FNProductionItem>();
            this.PRD_YearMonthCrustReqItem = new HashSet<PRD_YearMonthCrustReqItem>();
            this.PRD_YearMonthCrustReqItem1 = new HashSet<PRD_YearMonthCrustReqItem>();
            this.PRD_YearMonthCrustScheduleItem = new HashSet<PRD_YearMonthCrustScheduleItem>();
            this.PRD_YearMonthCrustScheduleItem1 = new HashSet<PRD_YearMonthCrustScheduleItem>();
            this.PRD_YearMonthFinishReqItem = new HashSet<PRD_YearMonthFinishReqItem>();
            this.PRD_YearMonthFinishReqItem1 = new HashSet<PRD_YearMonthFinishReqItem>();
            this.PRD_YearMonthFinishScheduleItem = new HashSet<PRD_YearMonthFinishScheduleItem>();
            this.PRD_YearMonthFinishScheduleItem1 = new HashSet<PRD_YearMonthFinishScheduleItem>();
            this.Sys_ArticleChallan = new HashSet<Sys_ArticleChallan>();
            this.Sys_ArticleChallan1 = new HashSet<Sys_ArticleChallan>();
            this.Sys_ArticleChallanColor = new HashSet<Sys_ArticleChallanColor>();
            this.Sys_ArticleChallanColor1 = new HashSet<Sys_ArticleChallanColor>();
            this.Sys_ArticleChallanDetail = new HashSet<Sys_ArticleChallanDetail>();
            this.Sys_ArticleChallanDetail1 = new HashSet<Sys_ArticleChallanDetail>();
            this.EXP_FreightBill = new HashSet<EXP_FreightBill>();
            this.EXP_FreightBill1 = new HashSet<EXP_FreightBill>();
            this.SLS_BuyerOrderDelivery = new HashSet<SLS_BuyerOrderDelivery>();
            this.SLS_BuyerOrderDelivery1 = new HashSet<SLS_BuyerOrderDelivery>();
            this.SLS_BuyerOrderPrice = new HashSet<SLS_BuyerOrderPrice>();
            this.SLS_BuyerOrderPrice1 = new HashSet<SLS_BuyerOrderPrice>();
            this.Sys_Comodity = new HashSet<Sys_Comodity>();
            this.Sys_Comodity1 = new HashSet<Sys_Comodity>();
            this.EXP_PIItem = new HashSet<EXP_PIItem>();
            this.EXP_PIItem1 = new HashSet<EXP_PIItem>();
            this.EXP_PIItemColor = new HashSet<EXP_PIItemColor>();
            this.EXP_PIItemColor1 = new HashSet<EXP_PIItemColor>();
            this.SLS_BuyerOrderItem = new HashSet<SLS_BuyerOrderItem>();
            this.SLS_BuyerOrderItem1 = new HashSet<SLS_BuyerOrderItem>();
            this.SLS_BuyerOrderItemColor = new HashSet<SLS_BuyerOrderItemColor>();
            this.SLS_BuyerOrderItemColor1 = new HashSet<SLS_BuyerOrderItemColor>();
            this.Sys_TransHead = new HashSet<Sys_TransHead>();
            this.Sys_TransHead1 = new HashSet<Sys_TransHead>();
            this.EXP_AgentCommissionBuyerCI = new HashSet<EXP_AgentCommissionBuyerCI>();
            this.EXP_AgentCommissionBuyerCI1 = new HashSet<EXP_AgentCommissionBuyerCI>();
            this.EXP_AgentCommission = new HashSet<EXP_AgentCommission>();
            this.EXP_AgentCommission1 = new HashSet<EXP_AgentCommission>();
            this.EXP_AgentCommission2 = new HashSet<EXP_AgentCommission>();
            this.EXP_BankLoan = new HashSet<EXP_BankLoan>();
            this.EXP_BankLoan1 = new HashSet<EXP_BankLoan>();
            this.EXP_BankLoan2 = new HashSet<EXP_BankLoan>();
            this.EXP_BankLoan3 = new HashSet<EXP_BankLoan>();
            this.EXP_BankVoucher = new HashSet<EXP_BankVoucher>();
            this.EXP_BankVoucher1 = new HashSet<EXP_BankVoucher>();
            this.EXP_BankVoucher2 = new HashSet<EXP_BankVoucher>();
            this.EXP_BankVoucher3 = new HashSet<EXP_BankVoucher>();
            this.EXP_BankVoucherDtl = new HashSet<EXP_BankVoucherDtl>();
            this.EXP_BankVoucherDtl1 = new HashSet<EXP_BankVoucherDtl>();
            this.EXP_BankVoucherDtl2 = new HashSet<EXP_BankVoucherDtl>();
            this.EXP_BankVoucherDtl3 = new HashSet<EXP_BankVoucherDtl>();
            this.EXP_BillofLadingContainer = new HashSet<EXP_BillofLadingContainer>();
            this.EXP_BillofLadingContainer1 = new HashSet<EXP_BillofLadingContainer>();
            this.LCM_BillofLadingContainer = new HashSet<LCM_BillofLadingContainer>();
            this.LCM_BillofLadingContainer1 = new HashSet<LCM_BillofLadingContainer>();
        }
    
        public int UserID { get; set; }
        public string UserCode { get; set; }
        public Nullable<byte> UserType { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> DesignationID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public int SupervisorUserID { get; set; }
        public string Description { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual ICollection<INV_ChemStockDaily> INV_ChemStockDaily { get; set; }
        public virtual ICollection<INV_ChemStockDaily> INV_ChemStockDaily1 { get; set; }
        public virtual ICollection<INV_ChemStockItem> INV_ChemStockItem { get; set; }
        public virtual ICollection<INV_ChemStockItem> INV_ChemStockItem1 { get; set; }
        public virtual ICollection<INV_ChemStockSupplier> INV_ChemStockSupplier { get; set; }
        public virtual ICollection<INV_ChemStockSupplier> INV_ChemStockSupplier1 { get; set; }
        public virtual ICollection<INV_CLTransfer> INV_CLTransfer { get; set; }
        public virtual ICollection<INV_CLTransfer> INV_CLTransfer1 { get; set; }
        public virtual ICollection<INV_CLTransfer> INV_CLTransfer2 { get; set; }
        public virtual ICollection<INV_CLTransfer> INV_CLTransfer3 { get; set; }
        public virtual ICollection<INV_CLTransfer> INV_CLTransfer4 { get; set; }
        public virtual ICollection<INV_CrustLeatherIssue> INV_CrustLeatherIssue { get; set; }
        public virtual ICollection<INV_CrustLeatherIssue> INV_CrustLeatherIssue1 { get; set; }
        public virtual ICollection<INV_CrustLeatherIssue> INV_CrustLeatherIssue2 { get; set; }
        public virtual ICollection<INV_CrustLeatherIssue> INV_CrustLeatherIssue3 { get; set; }
        public virtual ICollection<INV_StoreTrans> INV_StoreTrans { get; set; }
        public virtual ICollection<INV_StoreTrans> INV_StoreTrans1 { get; set; }
        public virtual ICollection<INV_StoreTrans> INV_StoreTrans2 { get; set; }
        public virtual ICollection<INV_StoreTransChallan> INV_StoreTransChallan { get; set; }
        public virtual ICollection<INV_StoreTransChallan> INV_StoreTransChallan1 { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem { get; set; }
        public virtual ICollection<INV_StoreTransItem> INV_StoreTransItem1 { get; set; }
        public virtual ICollection<INV_StoreTransRequest> INV_StoreTransRequest { get; set; }
        public virtual ICollection<INV_StoreTransRequest> INV_StoreTransRequest1 { get; set; }
        public virtual ICollection<INV_TransRequest> INV_TransRequest { get; set; }
        public virtual ICollection<INV_TransRequest> INV_TransRequest1 { get; set; }
        public virtual ICollection<INV_TransRequest> INV_TransRequest2 { get; set; }
        public virtual ICollection<INV_TransRequest> INV_TransRequest3 { get; set; }
        public virtual ICollection<INV_TransRequest> INV_TransRequest4 { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem { get; set; }
        public virtual ICollection<INV_TransRequestItem> INV_TransRequestItem1 { get; set; }
        public virtual ICollection<INV_TransRequestRef> INV_TransRequestRef { get; set; }
        public virtual ICollection<INV_TransRequestRef> INV_TransRequestRef1 { get; set; }
        public virtual ICollection<INV_TransRequestRef> INV_TransRequestRef2 { get; set; }
        public virtual ICollection<INV_WetBlueIssue> INV_WetBlueIssue { get; set; }
        public virtual ICollection<INV_WetBlueIssue> INV_WetBlueIssue1 { get; set; }
        public virtual ICollection<INV_WetBlueIssue> INV_WetBlueIssue2 { get; set; }
        public virtual ICollection<INV_WetBlueIssue> INV_WetBlueIssue3 { get; set; }
        public virtual ICollection<INV_WetBlueIssue> INV_WetBlueIssue4 { get; set; }
        public virtual ICollection<INV_WetBlueIssueItem> INV_WetBlueIssueItem { get; set; }
        public virtual ICollection<INV_WetBlueIssueItem> INV_WetBlueIssueItem1 { get; set; }
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher { get; set; }
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher1 { get; set; }
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher2 { get; set; }
        public virtual ICollection<LCM_BankDebitVoucher> LCM_BankDebitVoucher3 { get; set; }
        public virtual ICollection<LCM_BillofLading> LCM_BillofLading { get; set; }
        public virtual ICollection<LCM_BillofLading> LCM_BillofLading1 { get; set; }
        public virtual ICollection<LCM_BillofLading> LCM_BillofLading2 { get; set; }
        public virtual ICollection<LCM_CnfBill> LCM_CnfBill { get; set; }
        public virtual ICollection<LCM_CnfBill> LCM_CnfBill1 { get; set; }
        public virtual ICollection<LCM_CommercialInvoice> LCM_CommercialInvoice { get; set; }
        public virtual ICollection<LCM_CommercialInvoice> LCM_CommercialInvoice1 { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem { get; set; }
        public virtual ICollection<LCM_CommercialInvoiceItem> LCM_CommercialInvoiceItem1 { get; set; }
        public virtual ICollection<LCM_Insurence> LCM_Insurence { get; set; }
        public virtual ICollection<LCM_Insurence> LCM_Insurence1 { get; set; }
        public virtual ICollection<LCM_Insurence> LCM_Insurence2 { get; set; }
        public virtual ICollection<LCM_Insurence> LCM_Insurence3 { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening1 { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening2 { get; set; }
        public virtual ICollection<LCM_LCOpening> LCM_LCOpening3 { get; set; }
        public virtual ICollection<LCM_LCRetirement> LCM_LCRetirement { get; set; }
        public virtual ICollection<LCM_LCRetirement> LCM_LCRetirement1 { get; set; }
        public virtual ICollection<LCM_LimInfo> LCM_LimInfo { get; set; }
        public virtual ICollection<LCM_LimInfo> LCM_LimInfo1 { get; set; }
        public virtual ICollection<LCM_PackingList> LCM_PackingList { get; set; }
        public virtual ICollection<LCM_PackingList> LCM_PackingList1 { get; set; }
        public virtual ICollection<LCM_PackingList> LCM_PackingList2 { get; set; }
        public virtual ICollection<LCM_PackingListItem> LCM_PackingListItem { get; set; }
        public virtual ICollection<LCM_PackingListItem> LCM_PackingListItem1 { get; set; }
        public virtual ICollection<LCM_PackingListPacks> LCM_PackingListPacks { get; set; }
        public virtual ICollection<LCM_PackingListPacks> LCM_PackingListPacks1 { get; set; }
        public virtual ICollection<PRD_ChemProdReq> PRD_ChemProdReq { get; set; }
        public virtual ICollection<PRD_ChemProdReq> PRD_ChemProdReq1 { get; set; }
        public virtual ICollection<PRD_ChemProdReq> PRD_ChemProdReq2 { get; set; }
        public virtual ICollection<PRD_ChemProdReq> PRD_ChemProdReq3 { get; set; }
        public virtual ICollection<PRD_ChemProdReq> PRD_ChemProdReq4 { get; set; }
        public virtual ICollection<PRD_ChemProdReq> PRD_ChemProdReq5 { get; set; }
        public virtual ICollection<PRD_ChemProdReqItem> PRD_ChemProdReqItem { get; set; }
        public virtual ICollection<PRD_ChemProdReqItem> PRD_ChemProdReqItem1 { get; set; }
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction { get; set; }
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction1 { get; set; }
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction2 { get; set; }
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction3 { get; set; }
        public virtual ICollection<PRD_CLProduction> PRD_CLProduction4 { get; set; }
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical { get; set; }
        public virtual ICollection<PRD_CLProductionChemical> PRD_CLProductionChemical1 { get; set; }
        public virtual ICollection<PRD_CLProductionColor> PRD_CLProductionColor { get; set; }
        public virtual ICollection<PRD_CLProductionColor> PRD_CLProductionColor1 { get; set; }
        public virtual ICollection<PRD_CLProductionDrum> PRD_CLProductionDrum { get; set; }
        public virtual ICollection<PRD_CLProductionDrum> PRD_CLProductionDrum1 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQC> PRD_CrustLeatherQC { get; set; }
        public virtual ICollection<PRD_CrustLeatherQC> PRD_CrustLeatherQC1 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQC> PRD_CrustLeatherQC2 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQC> PRD_CrustLeatherQC3 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQC> PRD_CrustLeatherQC4 { get; set; }
        public virtual ICollection<PRD_Recipe> PRD_Recipe { get; set; }
        public virtual ICollection<PRD_Recipe> PRD_Recipe1 { get; set; }
        public virtual ICollection<PRD_RecipeItem> PRD_RecipeItem { get; set; }
        public virtual ICollection<PRD_RecipeItem> PRD_RecipeItem1 { get; set; }
        public virtual ICollection<PRD_WBProduction> PRD_WBProduction { get; set; }
        public virtual ICollection<PRD_WBProduction> PRD_WBProduction1 { get; set; }
        public virtual ICollection<PRD_WBProduction> PRD_WBProduction2 { get; set; }
        public virtual ICollection<PRD_WBProduction> PRD_WBProduction3 { get; set; }
        public virtual ICollection<PRD_WBProduction> PRD_WBProduction4 { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical { get; set; }
        public virtual ICollection<PRD_WBProductionChemical> PRD_WBProductionChemical1 { get; set; }
        public virtual ICollection<PRD_WBProductionPurchase> PRD_WBProductionPurchase { get; set; }
        public virtual ICollection<PRD_WBProductionPurchase> PRD_WBProductionPurchase1 { get; set; }
        public virtual ICollection<PRD_WBSelection> PRD_WBSelection { get; set; }
        public virtual ICollection<PRD_WBSelection> PRD_WBSelection1 { get; set; }
        public virtual ICollection<PRD_WBSelection> PRD_WBSelection2 { get; set; }
        public virtual ICollection<PRD_WBSelection> PRD_WBSelection3 { get; set; }
        public virtual ICollection<PRD_WBSelection> PRD_WBSelection4 { get; set; }
        public virtual ICollection<PRD_WBSelectionGrade> PRD_WBSelectionGrade { get; set; }
        public virtual ICollection<PRD_WBSelectionGrade> PRD_WBSelectionGrade1 { get; set; }
        public virtual ICollection<PRD_WBSellectionIssue> PRD_WBSellectionIssue { get; set; }
        public virtual ICollection<PRD_WBSellectionIssue> PRD_WBSellectionIssue1 { get; set; }
        public virtual ICollection<PRD_WBSellectionIssue> PRD_WBSellectionIssue2 { get; set; }
        public virtual ICollection<PRD_WBSellectionIssue> PRD_WBSellectionIssue3 { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueGrade> PRD_WBSellectionIssueGrade { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueGrade> PRD_WBSellectionIssueGrade1 { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueItem> PRD_WBSellectionIssueItem { get; set; }
        public virtual ICollection<PRD_WBSellectionIssueItem> PRD_WBSellectionIssueItem1 { get; set; }
        public virtual ICollection<PRD_YearMonth> PRD_YearMonth { get; set; }
        public virtual ICollection<PRD_YearMonth> PRD_YearMonth1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqDate> PRD_YearMonthCrustReqDate { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqDate> PRD_YearMonthCrustReqDate1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItemColor> PRD_YearMonthCrustReqItemColor { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItemColor> PRD_YearMonthCrustReqItemColor1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleColor> PRD_YearMonthCrustScheduleColor { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleColor> PRD_YearMonthCrustScheduleColor1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleDrum> PRD_YearMonthCrustScheduleDrum { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleDrum> PRD_YearMonthCrustScheduleDrum1 { get; set; }
        public virtual ICollection<PRD_YearMonthSchedule> PRD_YearMonthSchedule { get; set; }
        public virtual ICollection<PRD_YearMonthSchedule> PRD_YearMonthSchedule1 { get; set; }
        public virtual ICollection<PRD_YearMonthSchedule> PRD_YearMonthSchedule2 { get; set; }
        public virtual ICollection<PRD_YearMonthSchedule> PRD_YearMonthSchedule3 { get; set; }
        public virtual ICollection<PRD_YearMonthScheduleDate> PRD_YearMonthScheduleDate { get; set; }
        public virtual ICollection<PRD_YearMonthScheduleDate> PRD_YearMonthScheduleDate1 { get; set; }
        public virtual ICollection<PRD_YearMonthSchedulePurchase> PRD_YearMonthSchedulePurchase { get; set; }
        public virtual ICollection<PRD_YearMonthSchedulePurchase> PRD_YearMonthSchedulePurchase1 { get; set; }
        public virtual ICollection<PRQ_ChemBillPymtReference> PRQ_ChemBillPymtReference { get; set; }
        public virtual ICollection<PRQ_ChemBillPymtReference> PRQ_ChemBillPymtReference1 { get; set; }
        public virtual ICollection<PRQ_ChemBillRealization> PRQ_ChemBillRealization { get; set; }
        public virtual ICollection<PRQ_ChemBillRealization> PRQ_ChemBillRealization1 { get; set; }
        public virtual ICollection<PRQ_ChemBillRealization> PRQ_ChemBillRealization2 { get; set; }
        public virtual ICollection<PRQ_ChemBillRealization> PRQ_ChemBillRealization3 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr2 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdr> PRQ_ChemFrgnPurcOrdr3 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrItem> PRQ_ChemFrgnPurcOrdrItem1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrRqsn> PRQ_ChemFrgnPurcOrdrRqsn { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcOrdrRqsn> PRQ_ChemFrgnPurcOrdrRqsn1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecv> PRQ_ChemFrgnPurcRecv { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecv> PRQ_ChemFrgnPurcRecv1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecv> PRQ_ChemFrgnPurcRecv2 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecv> PRQ_ChemFrgnPurcRecv3 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvChallan> PRQ_ChemFrgnPurcRecvChallan { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvChallan> PRQ_ChemFrgnPurcRecvChallan1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvItem> PRQ_ChemFrgnPurcRecvItem1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvPL> PRQ_ChemFrgnPurcRecvPL { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvPL> PRQ_ChemFrgnPurcRecvPL1 { get; set; }
        public virtual ICollection<PRQ_ChemFrgnPurcRecvPL> PRQ_ChemFrgnPurcRecvPL2 { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI1 { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI2 { get; set; }
        public virtual ICollection<PRQ_ChemicalPI> PRQ_ChemicalPI3 { get; set; }
        public virtual ICollection<PRQ_ChemicalPIItem> PRQ_ChemicalPIItem { get; set; }
        public virtual ICollection<PRQ_ChemicalPIItem> PRQ_ChemicalPIItem1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBill> PRQ_ChemLocalPurcBill { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBill> PRQ_ChemLocalPurcBill1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBill> PRQ_ChemLocalPurcBill2 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBill> PRQ_ChemLocalPurcBill3 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillItem> PRQ_ChemLocalPurcBillItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillItem> PRQ_ChemLocalPurcBillItem1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillPayment> PRQ_ChemLocalPurcBillPayment { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillPayment> PRQ_ChemLocalPurcBillPayment1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillPayment> PRQ_ChemLocalPurcBillPayment2 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillPayment> PRQ_ChemLocalPurcBillPayment3 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillRef> PRQ_ChemLocalPurcBillRef { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcBillRef> PRQ_ChemLocalPurcBillRef1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecv> PRQ_ChemLocalPurcRecv { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecv> PRQ_ChemLocalPurcRecv1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecv> PRQ_ChemLocalPurcRecv2 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecv> PRQ_ChemLocalPurcRecv3 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvChallan> PRQ_ChemLocalPurcRecvChallan { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvChallan> PRQ_ChemLocalPurcRecvChallan1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvItem> PRQ_ChemLocalPurcRecvItem1 { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvPO> PRQ_ChemLocalPurcRecvPO { get; set; }
        public virtual ICollection<PRQ_ChemLocalPurcRecvPO> PRQ_ChemLocalPurcRecvPO1 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReq> PRQ_ChemPurcReq { get; set; }
        public virtual ICollection<PRQ_ChemPurcReq> PRQ_ChemPurcReq1 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReq> PRQ_ChemPurcReq2 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReq> PRQ_ChemPurcReq3 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReq> PRQ_ChemPurcReq4 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReq> PRQ_ChemPurcReq5 { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem { get; set; }
        public virtual ICollection<PRQ_ChemPurcReqItem> PRQ_ChemPurcReqItem1 { get; set; }
        public virtual ICollection<SLS_BuyerOrder> SLS_BuyerOrder { get; set; }
        public virtual ICollection<SLS_BuyerOrder> SLS_BuyerOrder1 { get; set; }
        public virtual ICollection<SLS_BuyerOrder> SLS_BuyerOrder2 { get; set; }
        public virtual ICollection<SLS_BuyerOrder> SLS_BuyerOrder3 { get; set; }
        public virtual ICollection<SLS_BuyerOrder> SLS_BuyerOrder4 { get; set; }
        public virtual ICollection<Sys_Article> Sys_Article { get; set; }
        public virtual ICollection<Sys_Article> Sys_Article1 { get; set; }
        public virtual ICollection<Sys_Bank> Sys_Bank { get; set; }
        public virtual ICollection<Sys_Bank> Sys_Bank1 { get; set; }
        public virtual ICollection<Sys_Branch> Sys_Branch { get; set; }
        public virtual ICollection<Sys_Branch> Sys_Branch1 { get; set; }
        public virtual ICollection<Sys_Buyer> Sys_Buyer { get; set; }
        public virtual ICollection<Sys_Buyer> Sys_Buyer1 { get; set; }
        public virtual ICollection<Sys_BuyerAddress> Sys_BuyerAddress { get; set; }
        public virtual ICollection<Sys_BuyerAddress> Sys_BuyerAddress1 { get; set; }
        public virtual ICollection<Sys_BuyerAgent> Sys_BuyerAgent { get; set; }
        public virtual ICollection<Sys_BuyerAgent> Sys_BuyerAgent1 { get; set; }
        public virtual ICollection<Sys_ChemicalItem> Sys_ChemicalItem { get; set; }
        public virtual ICollection<Sys_ChemicalItem> Sys_ChemicalItem1 { get; set; }
        public virtual ICollection<Sys_Color> Sys_Color { get; set; }
        public virtual ICollection<Sys_Color> Sys_Color1 { get; set; }
        public virtual ICollection<Sys_Country> Sys_Country { get; set; }
        public virtual ICollection<Sys_Country> Sys_Country1 { get; set; }
        public virtual ICollection<Sys_Machine> Sys_Machine { get; set; }
        public virtual ICollection<Sys_Machine> Sys_Machine1 { get; set; }
        public virtual ICollection<Sys_Port> Sys_Port { get; set; }
        public virtual ICollection<Sys_Port> Sys_Port1 { get; set; }
        public virtual ICollection<Sys_PreDefineValue> Sys_PreDefineValue { get; set; }
        public virtual ICollection<Sys_PreDefineValue> Sys_PreDefineValue1 { get; set; }
        public virtual ICollection<Sys_PreDefineValueFor> Sys_PreDefineValueFor { get; set; }
        public virtual ICollection<Sys_PreDefineValueFor> Sys_PreDefineValueFor1 { get; set; }
        public virtual ICollection<Sys_ProductionProces> Sys_ProductionProces { get; set; }
        public virtual ICollection<Sys_ProductionProces> Sys_ProductionProces1 { get; set; }
        public virtual ICollection<AccessLog> AccessLogs { get; set; }
        public virtual ICollection<AdditionalOperationPermission> AdditionalOperationPermissions { get; set; }
        public virtual ICollection<AdditionalScreenPermission> AdditionalScreenPermissions { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual UserCredentialInformation UserCredentialInformation { get; set; }
        public virtual ICollection<UserInRole> UserInRoles { get; set; }
        public virtual ICollection<INV_CLTransferFrom> INV_CLTransferFrom { get; set; }
        public virtual ICollection<INV_CLTransferFrom> INV_CLTransferFrom1 { get; set; }
        public virtual ICollection<INV_CLTransferTo> INV_CLTransferTo { get; set; }
        public virtual ICollection<INV_CLTransferTo> INV_CLTransferTo1 { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueColor> INV_CrustLeatherIssueColor { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueColor> INV_CrustLeatherIssueColor1 { get; set; }
        public virtual ICollection<PRD_WBSelectionItem> PRD_WBSelectionItem { get; set; }
        public virtual ICollection<PRD_WBSelectionItem> PRD_WBSelectionItem1 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCRef> PRD_CrustLeatherQCRef { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCRef> PRD_CrustLeatherQCRef1 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceive> INV_CrustLeatherReceive { get; set; }
        public virtual ICollection<INV_CrustLeatherReceive> INV_CrustLeatherReceive1 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceive> INV_CrustLeatherReceive2 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceive> INV_CrustLeatherReceive3 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveColor> INV_CrustLeatherReceiveColor { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveColor> INV_CrustLeatherReceiveColor1 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveItem> INV_CrustLeatherReceiveItem { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveItem> INV_CrustLeatherReceiveItem1 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveRef> INV_CrustLeatherReceiveRef { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveRef> INV_CrustLeatherReceiveRef1 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveRef> INV_CrustLeatherReceiveRef2 { get; set; }
        public virtual ICollection<INV_CrustLeatherReceiveRef> INV_CrustLeatherReceiveRef3 { get; set; }
        public virtual ICollection<INV_FinishLeatherIssue> INV_FinishLeatherIssue { get; set; }
        public virtual ICollection<INV_FinishLeatherIssue> INV_FinishLeatherIssue1 { get; set; }
        public virtual ICollection<INV_FinishLeatherIssue> INV_FinishLeatherIssue2 { get; set; }
        public virtual ICollection<INV_FinishLeatherIssue> INV_FinishLeatherIssue3 { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueColor> INV_FinishLeatherIssueColor { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueColor> INV_FinishLeatherIssueColor1 { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueItem> INV_FinishLeatherIssueItem { get; set; }
        public virtual ICollection<INV_FinishLeatherIssueItem> INV_FinishLeatherIssueItem1 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceive> INV_FinishLeatherReceive { get; set; }
        public virtual ICollection<INV_FinishLeatherReceive> INV_FinishLeatherReceive1 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceive> INV_FinishLeatherReceive2 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceive> INV_FinishLeatherReceive3 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveColor> INV_FinishLeatherReceiveColor { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveColor> INV_FinishLeatherReceiveColor1 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveItem> INV_FinishLeatherReceiveItem { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveItem> INV_FinishLeatherReceiveItem1 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveRef> INV_FinishLeatherReceiveRef { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveRef> INV_FinishLeatherReceiveRef1 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveRef> INV_FinishLeatherReceiveRef2 { get; set; }
        public virtual ICollection<INV_FinishLeatherReceiveRef> INV_FinishLeatherReceiveRef3 { get; set; }
        public virtual ICollection<INV_FNTransfer> INV_FNTransfer { get; set; }
        public virtual ICollection<INV_FNTransfer> INV_FNTransfer1 { get; set; }
        public virtual ICollection<INV_FNTransfer> INV_FNTransfer2 { get; set; }
        public virtual ICollection<INV_FNTransfer> INV_FNTransfer3 { get; set; }
        public virtual ICollection<INV_FNTransfer> INV_FNTransfer4 { get; set; }
        public virtual ICollection<INV_FNTransferFrom> INV_FNTransferFrom { get; set; }
        public virtual ICollection<INV_FNTransferFrom> INV_FNTransferFrom1 { get; set; }
        public virtual ICollection<INV_FNTransferTo> INV_FNTransferTo { get; set; }
        public virtual ICollection<INV_FNTransferTo> INV_FNTransferTo1 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQC> PRD_FinishLeatherQC { get; set; }
        public virtual ICollection<PRD_FinishLeatherQC> PRD_FinishLeatherQC1 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQC> PRD_FinishLeatherQC2 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQC> PRD_FinishLeatherQC3 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQC> PRD_FinishLeatherQC4 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCItem> PRD_FinishLeatherQCItem { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCItem> PRD_FinishLeatherQCItem1 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCRef> PRD_FinishLeatherQCRef { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCRef> PRD_FinishLeatherQCRef1 { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCSelection> PRD_FinishLeatherQCSelection { get; set; }
        public virtual ICollection<PRD_FinishLeatherQCSelection> PRD_FinishLeatherQCSelection1 { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction1 { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction2 { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction3 { get; set; }
        public virtual ICollection<PRD_FNProduction> PRD_FNProduction4 { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical { get; set; }
        public virtual ICollection<PRD_FNProductionChemical> PRD_FNProductionChemical1 { get; set; }
        public virtual ICollection<PRD_FNProductionColor> PRD_FNProductionColor { get; set; }
        public virtual ICollection<PRD_FNProductionColor> PRD_FNProductionColor1 { get; set; }
        public virtual ICollection<PRD_FNProductionDrum> PRD_FNProductionDrum { get; set; }
        public virtual ICollection<PRD_FNProductionDrum> PRD_FNProductionDrum1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqDate> PRD_YearMonthFinishReqDate { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqDate> PRD_YearMonthFinishReqDate1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItemColor> PRD_YearMonthFinishReqItemColor { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItemColor> PRD_YearMonthFinishReqItemColor1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleColor> PRD_YearMonthFinishScheduleColor { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleColor> PRD_YearMonthFinishScheduleColor1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleDrum> PRD_YearMonthFinishScheduleDrum { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleDrum> PRD_YearMonthFinishScheduleDrum1 { get; set; }
        public virtual ICollection<LCM_LCFile> LCM_LCFile { get; set; }
        public virtual ICollection<LCM_LCFile> LCM_LCFile1 { get; set; }
        public virtual ICollection<LCM_LCFile> LCM_LCFile2 { get; set; }
        public virtual ICollection<LCM_LCFile> LCM_LCFile3 { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord1 { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord2 { get; set; }
        public virtual ICollection<LCM_LCFileRecord> LCM_LCFileRecord3 { get; set; }
        public virtual ICollection<EXP_BillofLading> EXP_BillofLading { get; set; }
        public virtual ICollection<EXP_BillofLading> EXP_BillofLading1 { get; set; }
        public virtual ICollection<EXP_BillofLading> EXP_BillofLading2 { get; set; }
        public virtual ICollection<EXP_CI> EXP_CI { get; set; }
        public virtual ICollection<EXP_CI> EXP_CI1 { get; set; }
        public virtual ICollection<EXP_CIPI> EXP_CIPI { get; set; }
        public virtual ICollection<EXP_CIPI> EXP_CIPI1 { get; set; }
        public virtual ICollection<EXP_CnFBill> EXP_CnFBill { get; set; }
        public virtual ICollection<EXP_CnFBill> EXP_CnFBill1 { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening1 { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening2 { get; set; }
        public virtual ICollection<EXP_LCOpening> EXP_LCOpening3 { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI1 { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI2 { get; set; }
        public virtual ICollection<EXP_LeatherPI> EXP_LeatherPI3 { get; set; }
        public virtual ICollection<EXP_PackingList> EXP_PackingList { get; set; }
        public virtual ICollection<EXP_PackingList> EXP_PackingList1 { get; set; }
        public virtual ICollection<EXP_PackingList> EXP_PackingList2 { get; set; }
        public virtual ICollection<EXP_PLPI> EXP_PLPI { get; set; }
        public virtual ICollection<EXP_PLPI> EXP_PLPI1 { get; set; }
        public virtual ICollection<EXP_PLPIItemColorBale> EXP_PLPIItemColorBale { get; set; }
        public virtual ICollection<EXP_PLPIItemColorBale> EXP_PLPIItemColorBale1 { get; set; }
        public virtual ICollection<EXP_AgentCommissionBuyer> EXP_AgentCommissionBuyer { get; set; }
        public virtual ICollection<EXP_AgentCommissionBuyer> EXP_AgentCommissionBuyer1 { get; set; }
        public virtual ICollection<EXP_BankDebitVoucher> EXP_BankDebitVoucher { get; set; }
        public virtual ICollection<EXP_BankDebitVoucher> EXP_BankDebitVoucher1 { get; set; }
        public virtual ICollection<EXP_DeliveryChallan> EXP_DeliveryChallan { get; set; }
        public virtual ICollection<EXP_DeliveryChallan> EXP_DeliveryChallan1 { get; set; }
        public virtual ICollection<EXP_DeliveryChallan> EXP_DeliveryChallan2 { get; set; }
        public virtual ICollection<EXP_DeliveryChallanCI> EXP_DeliveryChallanCI { get; set; }
        public virtual ICollection<EXP_DeliveryChallanCI> EXP_DeliveryChallanCI1 { get; set; }
        public virtual ICollection<EXP_ExportForm> EXP_ExportForm { get; set; }
        public virtual ICollection<EXP_ExportForm> EXP_ExportForm1 { get; set; }
        public virtual ICollection<EXP_LCRetirement> EXP_LCRetirement { get; set; }
        public virtual ICollection<EXP_LCRetirement> EXP_LCRetirement1 { get; set; }
        public virtual ICollection<EXP_TransportChallan> EXP_TransportChallan { get; set; }
        public virtual ICollection<EXP_TransportChallan> EXP_TransportChallan1 { get; set; }
        public virtual ICollection<EXP_TransportChallan> EXP_TransportChallan2 { get; set; }
        public virtual ICollection<EXP_TransportChallanCI> EXP_TransportChallanCI { get; set; }
        public virtual ICollection<EXP_TransportChallanCI> EXP_TransportChallanCI1 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCItem> PRD_CrustLeatherQCItem { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCItem> PRD_CrustLeatherQCItem1 { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCSelection> PRD_CrustLeatherQCSelection { get; set; }
        public virtual ICollection<PRD_CrustLeatherQCSelection> PRD_CrustLeatherQCSelection1 { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueItem> INV_CrustLeatherIssueItem { get; set; }
        public virtual ICollection<INV_CrustLeatherIssueItem> INV_CrustLeatherIssueItem1 { get; set; }
        public virtual ICollection<EXP_CIPIItem> EXP_CIPIItem { get; set; }
        public virtual ICollection<EXP_CIPIItem> EXP_CIPIItem1 { get; set; }
        public virtual ICollection<EXP_CIPIItemColor> EXP_CIPIItemColor { get; set; }
        public virtual ICollection<EXP_CIPIItemColor> EXP_CIPIItemColor1 { get; set; }
        public virtual ICollection<EXP_PLPIItemColor> EXP_PLPIItemColor { get; set; }
        public virtual ICollection<EXP_PLPIItemColor> EXP_PLPIItemColor1 { get; set; }
        public virtual ICollection<INV_WetBlueIssueRef> INV_WetBlueIssueRef { get; set; }
        public virtual ICollection<INV_WetBlueIssueRef> INV_WetBlueIssueRef1 { get; set; }
        public virtual ICollection<PRD_CLProductionItem> PRD_CLProductionItem { get; set; }
        public virtual ICollection<PRD_CLProductionItem> PRD_CLProductionItem1 { get; set; }
        public virtual ICollection<PRD_FNProductionItem> PRD_FNProductionItem { get; set; }
        public virtual ICollection<PRD_FNProductionItem> PRD_FNProductionItem1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItem> PRD_YearMonthCrustReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthCrustReqItem> PRD_YearMonthCrustReqItem1 { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleItem> PRD_YearMonthCrustScheduleItem { get; set; }
        public virtual ICollection<PRD_YearMonthCrustScheduleItem> PRD_YearMonthCrustScheduleItem1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItem> PRD_YearMonthFinishReqItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishReqItem> PRD_YearMonthFinishReqItem1 { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleItem> PRD_YearMonthFinishScheduleItem { get; set; }
        public virtual ICollection<PRD_YearMonthFinishScheduleItem> PRD_YearMonthFinishScheduleItem1 { get; set; }
        public virtual ICollection<Sys_ArticleChallan> Sys_ArticleChallan { get; set; }
        public virtual ICollection<Sys_ArticleChallan> Sys_ArticleChallan1 { get; set; }
        public virtual ICollection<Sys_ArticleChallanColor> Sys_ArticleChallanColor { get; set; }
        public virtual ICollection<Sys_ArticleChallanColor> Sys_ArticleChallanColor1 { get; set; }
        public virtual ICollection<Sys_ArticleChallanDetail> Sys_ArticleChallanDetail { get; set; }
        public virtual ICollection<Sys_ArticleChallanDetail> Sys_ArticleChallanDetail1 { get; set; }
        public virtual Sys_CompanyInfo Sys_CompanyInfo { get; set; }
        public virtual ICollection<EXP_FreightBill> EXP_FreightBill { get; set; }
        public virtual ICollection<EXP_FreightBill> EXP_FreightBill1 { get; set; }
        public virtual ICollection<SLS_BuyerOrderDelivery> SLS_BuyerOrderDelivery { get; set; }
        public virtual ICollection<SLS_BuyerOrderDelivery> SLS_BuyerOrderDelivery1 { get; set; }
        public virtual ICollection<SLS_BuyerOrderPrice> SLS_BuyerOrderPrice { get; set; }
        public virtual ICollection<SLS_BuyerOrderPrice> SLS_BuyerOrderPrice1 { get; set; }
        public virtual ICollection<Sys_Comodity> Sys_Comodity { get; set; }
        public virtual ICollection<Sys_Comodity> Sys_Comodity1 { get; set; }
        public virtual ICollection<EXP_PIItem> EXP_PIItem { get; set; }
        public virtual ICollection<EXP_PIItem> EXP_PIItem1 { get; set; }
        public virtual ICollection<EXP_PIItemColor> EXP_PIItemColor { get; set; }
        public virtual ICollection<EXP_PIItemColor> EXP_PIItemColor1 { get; set; }
        public virtual ICollection<SLS_BuyerOrderItem> SLS_BuyerOrderItem { get; set; }
        public virtual ICollection<SLS_BuyerOrderItem> SLS_BuyerOrderItem1 { get; set; }
        public virtual ICollection<SLS_BuyerOrderItemColor> SLS_BuyerOrderItemColor { get; set; }
        public virtual ICollection<SLS_BuyerOrderItemColor> SLS_BuyerOrderItemColor1 { get; set; }
        public virtual ICollection<Sys_TransHead> Sys_TransHead { get; set; }
        public virtual ICollection<Sys_TransHead> Sys_TransHead1 { get; set; }
        public virtual ICollection<EXP_AgentCommissionBuyerCI> EXP_AgentCommissionBuyerCI { get; set; }
        public virtual ICollection<EXP_AgentCommissionBuyerCI> EXP_AgentCommissionBuyerCI1 { get; set; }
        public virtual ICollection<EXP_AgentCommission> EXP_AgentCommission { get; set; }
        public virtual ICollection<EXP_AgentCommission> EXP_AgentCommission1 { get; set; }
        public virtual ICollection<EXP_AgentCommission> EXP_AgentCommission2 { get; set; }
        public virtual ICollection<EXP_BankLoan> EXP_BankLoan { get; set; }
        public virtual ICollection<EXP_BankLoan> EXP_BankLoan1 { get; set; }
        public virtual ICollection<EXP_BankLoan> EXP_BankLoan2 { get; set; }
        public virtual ICollection<EXP_BankLoan> EXP_BankLoan3 { get; set; }
        public virtual ICollection<EXP_BankVoucher> EXP_BankVoucher { get; set; }
        public virtual ICollection<EXP_BankVoucher> EXP_BankVoucher1 { get; set; }
        public virtual ICollection<EXP_BankVoucher> EXP_BankVoucher2 { get; set; }
        public virtual ICollection<EXP_BankVoucher> EXP_BankVoucher3 { get; set; }
        public virtual ICollection<EXP_BankVoucherDtl> EXP_BankVoucherDtl { get; set; }
        public virtual ICollection<EXP_BankVoucherDtl> EXP_BankVoucherDtl1 { get; set; }
        public virtual ICollection<EXP_BankVoucherDtl> EXP_BankVoucherDtl2 { get; set; }
        public virtual ICollection<EXP_BankVoucherDtl> EXP_BankVoucherDtl3 { get; set; }
        public virtual ICollection<EXP_BillofLadingContainer> EXP_BillofLadingContainer { get; set; }
        public virtual ICollection<EXP_BillofLadingContainer> EXP_BillofLadingContainer1 { get; set; }
        public virtual ICollection<LCM_BillofLadingContainer> LCM_BillofLadingContainer { get; set; }
        public virtual ICollection<LCM_BillofLadingContainer> LCM_BillofLadingContainer1 { get; set; }
    }
}
