//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.DatabaseAccessLayer.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MenuInScreen
    {
        public int MenuID { get; set; }
        public string Caption { get; set; }
        public int ItemOrder { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string URL { get; set; }
        public short RoleID { get; set; }
    }
}
