//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityAdministration.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        public int AccessSerial { get; set; }
        public int UserID { get; set; }
        public string UserType { get; set; }
        public string LoginDeviceName { get; set; }
        public string LoginIPAddress { get; set; }
        public System.DateTime LoginTime { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
        public Nullable<byte> PasswordAttemptCount { get; set; }
        public System.DateTime SetOn { get; set; }
        public int SetBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
